import re
from rst_fast_parse.core import gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_, gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, gAAAAABmuydMZvEEZ_3jzwR8q9BsCcTFE50XNDCYTKN1JJpJvt4d7iPcmxP85UNh63Bidy8VWJ_6TQqrL0uFnzCWChXUvr1w_sY_V65KaX_WzQiRcnhAjbk_, gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__
from rst_fast_parse.elements import ListElement, ListItemElement
from rst_fast_parse._hijklmn.pppppppp import gAAAAABmuydMNNLzz9MdRqKgD2OoJuV_wTDkFmK_8qWedJgtCOi4hR1W7Vd2pAsqLCN6ufpFb3qb90VYbmxyzUowJ3HRQ76kQA__
from rst_fast_parse.source import gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__
from rst_fast_parse._opqrstu.tttttttt import gAAAAABmuydMtpIKrLY1a_pKduI6MueCkbIYGfpBRsBZiRWXongXyhPOvqKhvPJzED8BoZI18gBT9JeShqm9wsx8OHoZDYramttYMF63EzbtwZZh_M9vhbU_

def gAAAAABmuydMFQoYVRroxTsd4sVFHsrrXdUo_JXWopQ_6KCA4zA5qrpxJZPse4vpEpP2QFbB6E2BzquGOylsNxepWgQcx8pU3LGQ_uTsCR2EUZ3rfzXf3Vw_(source: gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__, parent: gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__, diagnostics: gAAAAABmuydMZvEEZ_3jzwR8q9BsCcTFE50XNDCYTKN1JJpJvt4d7iPcmxP85UNh63Bidy8VWJ_6TQqrL0uFnzCWChXUvr1w_sY_V65KaX_WzQiRcnhAjbk_, _: gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, /) -> gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_:
    if not (_gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__ := source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__):
        return gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_.gAAAAABmuydMNoVXrdqJvzMnoVrlYn_r3Ve1p2VbhCA8q06J5yPCK6aa322xvsPFlWI_vQyJJvvsEyWZHSCuNOqhrJs9iswRJw__
    if not re.match(gAAAAABmuydMNNLzz9MdRqKgD2OoJuV_wTDkFmK_8qWedJgtCOi4hR1W7Vd2pAsqLCN6ufpFb3qb90VYbmxyzUowJ3HRQ76kQA__, _gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.content):
        return gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_.gAAAAABmuydMKf1XPP798dMRx3PTLCDxb3oSW_v3i3TShC0b1ZBMlwGJvJcJxBiYfbIhB_70sjOifWGPv47p0bdjpiKqfq8JRA__
    items: list[ListItemElement] = []
    while (gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__ := source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__):
        if (match := re.match(gAAAAABmuydMNNLzz9MdRqKgD2OoJuV_wTDkFmK_8qWedJgtCOi4hR1W7Vd2pAsqLCN6ufpFb3qb90VYbmxyzUowJ3HRQ76kQA__, gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.content)):
            indent_length = match.end(0)
            content = source.gAAAAABmuydMYWGOiYMRJte2AIZmsTpE5T8M9dIG1126Umz8TRob4u_BOar5DbSoFetNDDhxxWklCW_tXtv5uahJjW5xiumYvoH9Ov5G2wj8XFPVuaa51dk_(first_indent=indent_length, until_blank=True, advance=True)
            list_item = ListItemElement((gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.line, gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.line if content.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ is None else content.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__.line))
            items.append(list_item)
            source.gAAAAABmuydMPNXekMCrPsz_vYOvYDs9_oPrgnfp3HgByoOHnDM0959v7DsbYZ6_m4qeg67gi4pyB8POEdOStAS6ZKU5A8yuhQ__()
        else:
            source.gAAAAABmuydMgGp1zxtMB3LqMXtilFCkg9VkTI4wy3_bYLi0JBOEylSKJahQoLf6NZZxDp0hhstN65CoqNG1cXLcS5Y3vvQntg__()
            break
    if items:
        parent.append(ListElement('line_block', items))
        gAAAAABmuydMtpIKrLY1a_pKduI6MueCkbIYGfpBRsBZiRWXongXyhPOvqKhvPJzED8BoZI18gBT9JeShqm9wsx8OHoZDYramttYMF63EzbtwZZh_M9vhbU_(diagnostics, source, 'Line block')
    return gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_.gAAAAABmuydM_3nhN_OjUBfPISsOcE6uNx7vcMNK1buxeJMBIyldcdVwhb7nmW0jrIJL4sgbZgUGzuOO7yr8rsz0gqVTH3yLwg__