from __future__ import annotations
import re
from rst_fast_parse._abcdefg.nnnnnnnn import gAAAAABmuydMS1adGH_315P3lgIZ_HOj8if5yfV3gRIo5AkPKLOLGJRJD5vRAS_qWnrwRRlPcssqDnYQK9bH7BRg83I7REbQVQ__
from rst_fast_parse.core import gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_, gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, gAAAAABmuydMZvEEZ_3jzwR8q9BsCcTFE50XNDCYTKN1JJpJvt4d7iPcmxP85UNh63Bidy8VWJ_6TQqrL0uFnzCWChXUvr1w_sY_V65KaX_WzQiRcnhAjbk_, gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__
from rst_fast_parse.elements import ListElement, ListItemElement
from rst_fast_parse._hijklmn.pppppppp import gAAAAABmuydMzaySbxZYTHdb4DqSkzRqgMG7bG_l_y1GLDtHVC8uxMuJLbnDaPvoWgb1qBxwYzCgzqdOk47Yxmjy43lLv9Xs3UaVpP1bwq2_evw2YSouWfk_
from rst_fast_parse.source import gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__
from rst_fast_parse._opqrstu.tttttttt import gAAAAABmuydMtpIKrLY1a_pKduI6MueCkbIYGfpBRsBZiRWXongXyhPOvqKhvPJzED8BoZI18gBT9JeShqm9wsx8OHoZDYramttYMF63EzbtwZZh_M9vhbU_

def gAAAAABmuydMXW9yvxUimpZitcC_HKoe4TQ8Ex9qDB33DNhFUcL4qYAH7s6cr6soGK6Vjs5yZp_wXtbfBP2YLHtDO_9kDRJE1jjjyTcUaaRdS_p330vRvAw_(source: gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__, parent: gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__, diagnostics: gAAAAABmuydMZvEEZ_3jzwR8q9BsCcTFE50XNDCYTKN1JJpJvt4d7iPcmxP85UNh63Bidy8VWJ_6TQqrL0uFnzCWChXUvr1w_sY_V65KaX_WzQiRcnhAjbk_, context: gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, /) -> gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_:
    if not (_gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__ := source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__):
        return gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_.gAAAAABmuydMNoVXrdqJvzMnoVrlYn_r3Ve1p2VbhCA8q06J5yPCK6aa322xvsPFlWI_vQyJJvvsEyWZHSCuNOqhrJs9iswRJw__
    if not (_ := re.match(gAAAAABmuydMzaySbxZYTHdb4DqSkzRqgMG7bG_l_y1GLDtHVC8uxMuJLbnDaPvoWgb1qBxwYzCgzqdOk47Yxmjy43lLv9Xs3UaVpP1bwq2_evw2YSouWfk_, _gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.content)):
        return gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_.gAAAAABmuydMKf1XPP798dMRx3PTLCDxb3oSW_v3i3TShC0b1ZBMlwGJvJcJxBiYfbIhB_70sjOifWGPv47p0bdjpiKqfq8JRA__
    items: list[ListItemElement] = []
    while (gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__ := source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__):
        if gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.gAAAAABmuydMLY3WjIO6PlM5TJMKh5cp2xHJZ8tGj9VdturoMbyEGZMJAjf88by_LCd3Uc0Zey3kyo4hBhWIoY_1QiOaoCkMhw__:
            source.gAAAAABmuydMPNXekMCrPsz_vYOvYDs9_oPrgnfp3HgByoOHnDM0959v7DsbYZ6_m4qeg67gi4pyB8POEdOStAS6ZKU5A8yuhQ__()
            continue
        if (match := re.match(gAAAAABmuydMzaySbxZYTHdb4DqSkzRqgMG7bG_l_y1GLDtHVC8uxMuJLbnDaPvoWgb1qBxwYzCgzqdOk47Yxmjy43lLv9Xs3UaVpP1bwq2_evw2YSouWfk_, gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.content)):
            initial_index = source.gAAAAABmuydMQMQdzY2n1tHKrwRTsUpxiPW2OqqLP9eBf7KORpmwkwSvf9RABCuoG0k0bcLTcCHDp_KM3j6YRj2bl5gKP8r_sA__
            content = source.gAAAAABmuydMYWGOiYMRJte2AIZmsTpE5T8M9dIG1126Umz8TRob4u_BOar5DbSoFetNDDhxxWklCW_tXtv5uahJjW5xiumYvoH9Ov5G2wj8XFPVuaa51dk_(first_indent=match.end(0), advance=True)
            if not content.gAAAAABmuydMXfz1AIWsDgOdvVKP_SILNaxE0ylZV_A_akbaeqa_npXrVtV5E2u50LBGu_ktj_Zi_MsSX26YZl_W2zZEZNSEYA__():
                source.gAAAAABmuydM3NOsP8_2N_P1DhbJSfRKMpm8xz4o9uW1S9A5rgppUUk4eOd9MT4pm1aHwvBrbp7GuicEAJRd9X4Y61XkFnXwpTdmBwHvGeMvatPvcegjz5g_(initial_index)
                if items:
                    parent.append(ListElement('option_list', items))
                    gAAAAABmuydMtpIKrLY1a_pKduI6MueCkbIYGfpBRsBZiRWXongXyhPOvqKhvPJzED8BoZI18gBT9JeShqm9wsx8OHoZDYramttYMF63EzbtwZZh_M9vhbU_(diagnostics, source, 'Option list')
                return gAAAAABmuydMS1adGH_315P3lgIZ_HOj8if5yfV3gRIo5AkPKLOLGJRJD5vRAS_qWnrwRRlPcssqDnYQK9bH7BRg83I7REbQVQ__(source, parent, diagnostics, context)
            list_item = ListItemElement((gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.line, gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.line if content.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ is None else content.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__.line))
            items.append(list_item)
            context.gAAAAABmuydMMF7ZY53udCcS2ALzNb0Tz_DMP3IixR1JcbpUdl3ynb7luBKHkl8sLLd7on9MRLssGnahjwAivbf9MRBXSFHPbg__(content, list_item, diagnostics)
            source.gAAAAABmuydMPNXekMCrPsz_vYOvYDs9_oPrgnfp3HgByoOHnDM0959v7DsbYZ6_m4qeg67gi4pyB8POEdOStAS6ZKU5A8yuhQ__()
        else:
            source.gAAAAABmuydMgGp1zxtMB3LqMXtilFCkg9VkTI4wy3_bYLi0JBOEylSKJahQoLf6NZZxDp0hhstN65CoqNG1cXLcS5Y3vvQntg__()
            break
    if items:
        parent.append(ListElement('option_list', items))
        gAAAAABmuydMtpIKrLY1a_pKduI6MueCkbIYGfpBRsBZiRWXongXyhPOvqKhvPJzED8BoZI18gBT9JeShqm9wsx8OHoZDYramttYMF63EzbtwZZh_M9vhbU_(diagnostics, source, 'Option list')
    return gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_.gAAAAABmuydM_3nhN_OjUBfPISsOcE6uNx7vcMNK1buxeJMBIyldcdVwhb7nmW0jrIJL4sgbZgUGzuOO7yr8rsz0gqVTH3yLwg__