from __future__ import annotations
import re
from rst_fast_parse.core import gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_, gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, gAAAAABmuydMZvEEZ_3jzwR8q9BsCcTFE50XNDCYTKN1JJpJvt4d7iPcmxP85UNh63Bidy8VWJ_6TQqrL0uFnzCWChXUvr1w_sY_V65KaX_WzQiRcnhAjbk_, gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__
from rst_fast_parse.diagnostics import Diagnostic, DiagnosticCode
from rst_fast_parse.elements import BasicElement, DirectiveElement, LinkTargetElement
from rst_fast_parse._hijklmn.pppppppp import gAAAAABmuydMWYmUVzFNIsu2CaKCi8pSWtE1mtdhcEtT2fUYpdo8Ch5ur1h8_Z1fRfjvo1CRgSlsTckHwTGo9xr6OFoXa9VpJgmNxojMiRFHZ3VTPxXzSTk_, gAAAAABmuydME4fpzBTUgoeTyEC0j0XehtX0HgrcB7d03igPaHoam0lexMCS1oEpiOhRK5rWp6R1NqRKV7U_7vTmbd1E4NMGxg__, gAAAAABmuydMWR31g6PcHt0FWYTZTgLEc2CZ5P_eS7Nll05HB0BT7AgOSFLlBSs5R1adP8evzI8oQ631LRdZFiz48DGNIgOkVFAIG0Kt0DbOkvskjdJ1JpM_, gAAAAABmuydMXhCtFhLYmQ7lzsabZecb_UO_J1Mh47FeDmdiuwhFM8myedVJwTr_otNBruKc4VzngCO3RN7rylvQlDtq60rLtfBGyifjL87UikG8TwzPldo_, gAAAAABmuydMkQW4OCDbgRZQ6efKB1srT7t4BdWE2cuvvAIy5vJ2ncDSohC5DYuKVGlbhj6_fkpx3LEan2CO7T4ibFVraCeLQMH1nsjFPTsJw_zZY5oBB1A_, gAAAAABmuydMtbyBEbd0ue1aNKSjqa8_hqR7m3_16DswgAyJMX88jNxew9bHI6NkwFuT__nHEXy1NVcyUTqAlZqbPSWqt9M2SaXk2uhDjK9x_Wl__g2Wx4k_, gAAAAABmuydMvzUC_3oyJQLBB6WZL1MRjXtxElD9Q5wr6y7hSgkbZuiY6HAie4uVtfji4qVs5V_5al7N0BmFJMU4ycCms_UndXt3aOgQLVRS2RcCzBts_tM_, gAAAAABmuydMatreUy0pTUYpf1W3V9r9AcXnNE7_cDf_coIxIBIG2_9UdzkqVD3sCzHCw05q1N08931oTb0bvFL8gV7_S_vmNFkPuKTI8z05UJmTBhsSt3c_
from rst_fast_parse.source import PositiveInt, gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__
from rst_fast_parse._opqrstu.tttttttt import gAAAAABmuydMelSFXO62LPEPZaDQYnZkNrTCbGsS0_M8oQuAOZ21p_Oont3gUmCGLI_1o1Tj2Zm4NrV_mVZYs_MQnK2qQpQzIZI26UjQMYC2pwta1tGFuZY_
from rst_fast_parse._opqrstu.rrrrrrrr import EscapedStr, gAAAAABmuydMPtls5CUMo4erY_jQ1TheJVFpl8HAqeRri9_rhhWIJrda9Yub4Uvd5f_gKwEQ6IEM95TCD8LOzlPvMlhxft3lIw__, gAAAAABmuydMiEstuu8RD1fjnJiyhjBfoPmwpwnvYhRdcpXnN0E9zwayiK__30RnJtz2MObxTiDpfu_i0v2CEjG_ENTVBnHqoA__, gAAAAABmuydML19K8X75ay8cEWNwmjBmjTUqw9mjKLZRoIzpHQod13eo0PQ7nIDleSKX_JHkvc78D40g8_rHkp6IFIkUD_AI71eTKto2uhZj2YZUkxWx60E_
from rst_fast_parse._opqrstu.ssssssss import gAAAAABmuydM2FxmvGrdj_p8wf7TZpIzka0q5bCtUObDberOTfudzWM3WuCU7_M91m2blbECNhIJmI6guQRol1bv71bVgp_KnrayFHUllLe64UDrF6eeGyk_

def gAAAAABmuydM1W2PvsmnRNPl1zjCEgcPPJs84W2e_nYj2Sz9QMghfkDV4BCmsD_aggt3lctorJhZFuIxurp1jjoZS0x_bFqeGc1Q0JD3C8aT8eQkrH9ekL0_(source: gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__, parent: gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__, diagnostics: gAAAAABmuydMZvEEZ_3jzwR8q9BsCcTFE50XNDCYTKN1JJpJvt4d7iPcmxP85UNh63Bidy8VWJ_6TQqrL0uFnzCWChXUvr1w_sY_V65KaX_WzQiRcnhAjbk_, context: gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, /) -> gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_:
    if not (gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__ := source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__):
        return gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_.gAAAAABmuydMNoVXrdqJvzMnoVrlYn_r3Ve1p2VbhCA8q06J5yPCK6aa322xvsPFlWI_vQyJJvvsEyWZHSCuNOqhrJs9iswRJw__
    if not (init_match := re.match(gAAAAABmuydME4fpzBTUgoeTyEC0j0XehtX0HgrcB7d03igPaHoam0lexMCS1oEpiOhRK5rWp6R1NqRKV7U_7vTmbd1E4NMGxg__, gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.content)):
        return gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_.gAAAAABmuydMKf1XPP798dMRx3PTLCDxb3oSW_v3i3TShC0b1ZBMlwGJvJcJxBiYfbIhB_70sjOifWGPv47p0bdjpiKqfq8JRA__
    if (match := re.match(gAAAAABmuydMkQW4OCDbgRZQ6efKB1srT7t4BdWE2cuvvAIy5vJ2ncDSohC5DYuKVGlbhj6_fkpx3LEan2CO7T4ibFVraCeLQMH1nsjFPTsJw_zZY5oBB1A_, gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.content)):
        gAAAAABmuydMTPaayU6B3MGi8940IgGJcNWQv_iSx9AFQzEomNo_6dCpnoWMB04H3GzoZh_BSfdPrABNl4zib4ssC_jGki4SQQ__(source, parent, context, match)
    elif (match := re.match(gAAAAABmuydMWR31g6PcHt0FWYTZTgLEc2CZ5P_eS7Nll05HB0BT7AgOSFLlBSs5R1adP8evzI8oQ631LRdZFiz48DGNIgOkVFAIG0Kt0DbOkvskjdJ1JpM_, gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.content)):
        gAAAAABmuydMltbopLF59X4nLUZ0JnulnVcRAZS73CmI1x0tZQnWOyPq09HZ87OMWMwLTui5hPMwsbJaTmeo1iyCt_3zOR7qBg__(source, parent, context, match)
    elif (match := re.match(gAAAAABmuydMvzUC_3oyJQLBB6WZL1MRjXtxElD9Q5wr6y7hSgkbZuiY6HAie4uVtfji4qVs5V_5al7N0BmFJMU4ycCms_UndXt3aOgQLVRS2RcCzBts_tM_, gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.content)):
        gAAAAABmuydMaHPSI8WJCpZ6OzLDnCdNbNJGvA031_RwwbgDjoHnhy48zbAOnmlwCcemw5pbp33E_chHXPycNY5lJ6sekl1CII9iWWOQxnWGnPcwm_9dQRU_(source, parent, diagnostics, context, match)
    elif (match := re.match(gAAAAABmuydMtbyBEbd0ue1aNKSjqa8_hqR7m3_16DswgAyJMX88jNxew9bHI6NkwFuT__nHEXy1NVcyUTqAlZqbPSWqt9M2SaXk2uhDjK9x_Wl__g2Wx4k_, gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.content)):
        gAAAAABmuydMToGGJRCZVdZe79_u8AZb5DDgPJXu4QPVPaGqAzR8UbKCqobp0iLqblRY_rDLGFAj0FovuITCCIR9qwqzkmx0sGguTPn6ZfpRElgXZyiKGRI_(source, parent, context, match)
    elif (match := re.match(gAAAAABmuydMXhCtFhLYmQ7lzsabZecb_UO_J1Mh47FeDmdiuwhFM8myedVJwTr_otNBruKc4VzngCO3RN7rylvQlDtq60rLtfBGyifjL87UikG8TwzPldo_, gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.content)):
        gAAAAABmuydM473nPOyeKeCRfJ__PbQZGtQyh_X_MzKKeYzkV3mRGG87Wcf10lZTQFSiRkZaesvGi4uMHQT7J6ZLK0NY6WIKUA__(source, parent, context, match)
    else:
        gAAAAABmuydMGi1_qWUS3d5LAc8FdShVV8Uvs_XE19O5BoLZFxbuhc_gir9hvG4oHrqEY_KqpKl5WZjAtba1Pk71XERj2gEINQ__(source, parent, context, init_match.end(0))
    if not source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.gAAAAABmuydMLY3WjIO6PlM5TJMKh5cp2xHJZ8tGj9VdturoMbyEGZMJAjf88by_LCd3Uc0Zey3kyo4hBhWIoY_1QiOaoCkMhw__ and (next_line := source.gAAAAABmuydMjbS8YuuKhsP69b_LVvC78esxs5XU17tNBvFT5M78twv9zAr2BCdXDlxxlpryRxHeuS9otaesRd8zMuXC_yzrRg__()) and (not next_line.gAAAAABmuydMLY3WjIO6PlM5TJMKh5cp2xHJZ8tGj9VdturoMbyEGZMJAjf88by_LCd3Uc0Zey3kyo4hBhWIoY_1QiOaoCkMhw__) and (not (re.match(gAAAAABmuydME4fpzBTUgoeTyEC0j0XehtX0HgrcB7d03igPaHoam0lexMCS1oEpiOhRK5rWp6R1NqRKV7U_7vTmbd1E4NMGxg__, next_line.content) or re.match(gAAAAABmuydMWYmUVzFNIsu2CaKCi8pSWtE1mtdhcEtT2fUYpdo8Ch5ur1h8_Z1fRfjvo1CRgSlsTckHwTGo9xr6OFoXa9VpJgmNxojMiRFHZ3VTPxXzSTk_, next_line.content))):
        diagnostics.append(gAAAAABmuydMelSFXO62LPEPZaDQYnZkNrTCbGsS0_M8oQuAOZ21p_Oont3gUmCGLI_1o1Tj2Zm4NrV_mVZYs_MQnK2qQpQzIZI26UjQMYC2pwta1tGFuZY_(source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__, 'explicit markup'))
    return gAAAAABmuydMQpIcseTp2a_x6vkRdemQi7BjIjLK54WK1Euw2x2tfrfcFC7KFRL7hwgsVYK0hMaWeW2NVkRVAoQcY5g5bUdvdHEmjIYcUhrtREWBxAS7Acw_.gAAAAABmuydM_3nhN_OjUBfPISsOcE6uNx7vcMNK1buxeJMBIyldcdVwhb7nmW0jrIJL4sgbZgUGzuOO7yr8rsz0gqVTH3yLwg__

def gAAAAABmuydMTPaayU6B3MGi8940IgGJcNWQv_iSx9AFQzEomNo_6dCpnoWMB04H3GzoZh_BSfdPrABNl4zib4ssC_jGki4SQQ__(source: gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__, parent: gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__, context: gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, match: re.Match[str]) -> None:
    first = source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__
    slice = source.gAAAAABmuydMYWGOiYMRJte2AIZmsTpE5T8M9dIG1126Umz8TRob4u_BOar5DbSoFetNDDhxxWklCW_tXtv5uahJjW5xiumYvoH9Ov5G2wj8XFPVuaa51dk_(first_indent=match.end(0), advance=True)
    last = slice.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ if slice.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ is not None else source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__
    if first and last:
        parent.append(BasicElement('footnote', (first.line, last.line)))

def gAAAAABmuydMltbopLF59X4nLUZ0JnulnVcRAZS73CmI1x0tZQnWOyPq09HZ87OMWMwLTui5hPMwsbJaTmeo1iyCt_3zOR7qBg__(source: gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__, parent: gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__, context: gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, match: re.Match[str]) -> None:
    first = source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__
    slice = source.gAAAAABmuydMYWGOiYMRJte2AIZmsTpE5T8M9dIG1126Umz8TRob4u_BOar5DbSoFetNDDhxxWklCW_tXtv5uahJjW5xiumYvoH9Ov5G2wj8XFPVuaa51dk_(first_indent=match.end(0), advance=True)
    last = slice.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ if slice.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ is not None else source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__
    if first and last:
        parent.append(BasicElement('citation', (first.line, last.line)))

def gAAAAABmuydMaHPSI8WJCpZ6OzLDnCdNbNJGvA031_RwwbgDjoHnhy48zbAOnmlwCcemw5pbp33E_chHXPycNY5lJ6sekl1CII9iWWOQxnWGnPcwm_9dQRU_(source: gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__, parent: gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__, diagnostics: gAAAAABmuydMZvEEZ_3jzwR8q9BsCcTFE50XNDCYTKN1JJpJvt4d7iPcmxP85UNh63Bidy8VWJ_6TQqrL0uFnzCWChXUvr1w_sY_V65KaX_WzQiRcnhAjbk_, context: gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, match: re.Match[str]) -> None:
    init_line_index = source.gAAAAABmuydMQMQdzY2n1tHKrwRTsUpxiPW2OqqLP9eBf7KORpmwkwSvf9RABCuoG0k0bcLTcCHDp_KM3j6YRj2bl5gKP8r_sA__
    first = source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__
    slice = source.gAAAAABmuydMYWGOiYMRJte2AIZmsTpE5T8M9dIG1126Umz8TRob4u_BOar5DbSoFetNDDhxxWklCW_tXtv5uahJjW5xiumYvoH9Ov5G2wj8XFPVuaa51dk_(first_indent=match.end(0), until_blank=True, advance=True, strip_indent=False)
    escaped_lines = [gAAAAABmuydMPtls5CUMo4erY_jQ1TheJVFpl8HAqeRri9_rhhWIJrda9Yub4Uvd5f_gKwEQ6IEM95TCD8LOzlPvMlhxft3lIw__(line.content) for line in slice.gAAAAABmuydMPlSfgmYqlXEaJj4C82lAXKX89P7rqaNLHrOkC0Vlq5ViJ4MOUw1laSnp4veTcGvRCoXfpY9TrO3ccwvzqBEoCA__()]
    prefix = escaped_lines[0]
    blockindex = 0
    while True:
        if (target_match := re.match(gAAAAABmuydMatreUy0pTUYpf1W3V9r9AcXnNE7_cDf_coIxIBIG2_9UdzkqVD3sCzHCw05q1N08931oTb0bvFL8gV7_S_vmNFkPuKTI8z05UJmTBhsSt3c_, prefix)):
            escaped_name: EscapedStr | None = target_match.group('name')
            name = None if escaped_name is None else gAAAAABmuydML19K8X75ay8cEWNwmjBmjTUqw9mjKLZRoIzpHQod13eo0PQ7nIDleSKX_JHkvc78D40g8_rHkp6IFIkUD_AI71eTKto2uhZj2YZUkxWx60E_(escaped_name)
            norm_name = None if escaped_name is None else gAAAAABmuydM2FxmvGrdj_p8wf7TZpIzka0q5bCtUObDberOTfudzWM3WuCU7_M91m2blbECNhIJmI6guQRol1bv71bVgp_KnrayFHUllLe64UDrF6eeGyk_(gAAAAABmuydMiEstuu8RD1fjnJiyhjBfoPmwpwnvYhRdcpXnN0E9zwayiK__30RnJtz2MObxTiDpfu_i0v2CEjG_ENTVBnHqoA__(escaped_name))
            break
        blockindex += 1
        try:
            prefix += escaped_lines[blockindex]
        except IndexError:
            source.gAAAAABmuydM3NOsP8_2N_P1DhbJSfRKMpm8xz4o9uW1S9A5rgppUUk4eOd9MT4pm1aHwvBrbp7GuicEAJRd9X4Y61XkFnXwpTdmBwHvGeMvatPvcegjz5g_(init_line_index)
            gAAAAABmuydMGi1_qWUS3d5LAc8FdShVV8Uvs_XE19O5BoLZFxbuhc_gir9hvG4oHrqEY_KqpKl5WZjAtba1Pk71XERj2gEINQ__(source, parent, context, match.end(0) - 1)
            diagnostics.append(Diagnostic(DiagnosticCode.target_malformed, 'malformed hyperlink target; no delimiter found.', slice.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.line))
            return
    last = slice.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ if slice.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ is not None else source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__
    if first and last:
        parent.append(LinkTargetElement(name, norm_name, (first.line, last.line)))

def gAAAAABmuydMToGGJRCZVdZe79_u8AZb5DDgPJXu4QPVPaGqAzR8UbKCqobp0iLqblRY_rDLGFAj0FovuITCCIR9qwqzkmx0sGguTPn6ZfpRElgXZyiKGRI_(source: gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__, parent: gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__, context: gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, match: re.Match[str]) -> None:
    first = source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__
    slice = source.gAAAAABmuydMYWGOiYMRJte2AIZmsTpE5T8M9dIG1126Umz8TRob4u_BOar5DbSoFetNDDhxxWklCW_tXtv5uahJjW5xiumYvoH9Ov5G2wj8XFPVuaa51dk_(first_indent=match.end(0), strip_indent=False, advance=True)
    last = slice.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ if slice.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ is not None else source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__
    if first and last:
        parent.append(BasicElement('substitution_def', (first.line, last.line)))

def gAAAAABmuydM473nPOyeKeCRfJ__PbQZGtQyh_X_MzKKeYzkV3mRGG87Wcf10lZTQFSiRkZaesvGi4uMHQT7J6ZLK0NY6WIKUA__(source: gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__, parent: gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__, context: gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, match: re.Match[str]) -> None:
    first = source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__
    slice = source.gAAAAABmuydMYWGOiYMRJte2AIZmsTpE5T8M9dIG1126Umz8TRob4u_BOar5DbSoFetNDDhxxWklCW_tXtv5uahJjW5xiumYvoH9Ov5G2wj8XFPVuaa51dk_(first_indent=match.end(0), strip_top=False, advance=True)
    last = slice.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ if slice.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__ is not None else source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__
    if first and last:
        parent.append(DirectiveElement(match.group(1), (first.line, last.line)))

def gAAAAABmuydMGi1_qWUS3d5LAc8FdShVV8Uvs_XE19O5BoLZFxbuhc_gir9hvG4oHrqEY_KqpKl5WZjAtba1Pk71XERj2gEINQ__(source: gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__, parent: gAAAAABmuydMRweAvNUw6_RAhvNTsyROtSlhzkieQGDs7aJ4PmDgfnBl2w5qXfrC0rD9MRHqzLLKUy6bmJaLqiC8ueZoeMhy1g__, _: gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__, first_indent: int) -> None:
    if not source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__:
        return
    first = source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__
    if (next_line := source.gAAAAABmuydMjbS8YuuKhsP69b_LVvC78esxs5XU17tNBvFT5M78twv9zAr2BCdXDlxxlpryRxHeuS9otaesRd8zMuXC_yzrRg__(1)) is not None and next_line.gAAAAABmuydMLY3WjIO6PlM5TJMKh5cp2xHJZ8tGj9VdturoMbyEGZMJAjf88by_LCd3Uc0Zey3kyo4hBhWIoY_1QiOaoCkMhw__:
        first_indent = PositiveInt(first_indent)
        if source.gAAAAABmuydMWORmKn5jshVdawl0HXIIyAiSOnnJ4Ye5DISO6vjqv641ervwhm7rY79I_nPWObfGoHnHKGRsoyiMlWwMmaEmJA__.gAAAAABmuydMIA0LSLzqw0txEKH3s3l7DiurA_YCUndDfzUr4FO5oo_5OcOoNHNxYlRgFct6oxOZ4lOYNxxYoZ4By4r46EDGaw__(first_indent).gAAAAABmuydMLY3WjIO6PlM5TJMKh5cp2xHJZ8tGj9VdturoMbyEGZMJAjf88by_LCd3Uc0Zey3kyo4hBhWIoY_1QiOaoCkMhw__:
            parent.append(BasicElement('comment', (first.line, first.line)))
            return
    slice = source.gAAAAABmuydMYWGOiYMRJte2AIZmsTpE5T8M9dIG1126Umz8TRob4u_BOar5DbSoFetNDDhxxWklCW_tXtv5uahJjW5xiumYvoH9Ov5G2wj8XFPVuaa51dk_(first_indent=first_indent, strip_bottom=True, advance=True)
    if (last := slice.gAAAAABmuydMMDFHabcSdIh9mauc3_cVL_vPmICOToRMyXe24NJkI8PyaMKTQge2_LiSPcI2oRpWHdyIgMadE8ZUyD8xCSnCKQ__):
        parent.append(BasicElement('comment', (first.line, last.line)))