
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked docsource archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-14T14:28:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8d399fec5181d458afe8d8f46450b0a8534fd98",
 "version": "1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
