
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-15T15:42:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4efeb81c1fcf45b18d78b58169235604dfd72bd6",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
