NEW_ATTRIBUTE_MAP = {
    "originalCallDate": '//span[text()="Original Call Date:"]/following-sibling::span[last()]',
    "ticketNumber": '//span[text()="Ticket No:"]/following-sibling::span[last()]',
    "callType": '//span[text()="Original Call Date:"]/parent::div/following-sibling::div/span[last()]',
    "expirationDate": '//span[text()="Expiration Date:"]/following-sibling::span[last()]',
    "callerName": '//span[text()="Caller Name:"]/following-sibling::span[last()]',
    "callerPhone": '//span[text()="Caller Name:"]/parent::div/following-sibling::div/span[text()="Phone:"]/following-sibling::span[last()]',
    "excavatorName": '//span[text()="Excavator Name:"]/following-sibling::span[last()]',
    "excavatorPhone": '//span[text()="Excavator Name:"]/parent::div/following-sibling::div/span[text()="Phone:"]/following-sibling::span[last()]',
    "excavatorAddress": '//span[text()="Excavator Name:"]/parent::div/following-sibling::div/following-sibling::div/span[text()="Address:"]/following-sibling::span[last()]',
    "excavatorEmail": '//span[text()="Contact Email:"]/following-sibling::span[last()]',
    "onsiteContact": '//span[text()="Onsite Contact:"]/following-sibling::span[last()]',
    "onsitePhone": '//span[text()="Onsite Contact:"]/parent::div/following-sibling::div/span[text()="Phone:"]/following-sibling::span[last()]',
    "beginWorkDate": '//span[text()="Beginning Work Date:"]/following-sibling::span[last()]',
    "workDuration": '//span[text()="Duration:"]/following-sibling::span[last()]',
    "workType": '//span[text()="Type of Work:"]/following-sibling::span[last()]',
    "workDoneFor": '//span[text()="Work Being Done For:"]/following-sibling::span[last()]',
    "trenching": '//span[text()="Trenching:"]/following-sibling::span[last()]',
    "boring": '//span[text()="Boring:"]/following-sibling::span[last()]',
    "plowing": '//span[text()="Plowing:"]/following-sibling::span[last()]',
    "backhoe": '//span[text()="Backhoe:"]/following-sibling::span[last()]',
    "blasting": '//span[text()="Blasting:"]/following-sibling::span[last()]',
    "other": '//span[text()="Other:"]/following-sibling::span[last()]',
    "markedWhite": '//span[text()="Marked in White:"]/following-sibling::span[last()]',
    "digCounty": '//span[text()="County:"]/following-sibling::span[last()]',
    "digCity": '//span[text()="City:"]/following-sibling::span[last()]',
    "digAddress": '//span[text()="City Limits:"]/parent::div/following-sibling::div//span[last()]',
    "digAddressAt": '//span[text()="At:"]/following-sibling::span[last()]',
    "extentOfWork": '//td[text()="Location of Work:"]/following-sibling::td/span[last()]',
    "remarks": '//span[text()="Remarks:"]/following-sibling::span[last()]',
    "deadline": '//span[text()="Locates shall be completed no later than:"]/following-sibling::span[last()]',
    "status": None,
    "lastAutomaticUpdate": None
}