"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .walletcounterpartaccount import WalletCounterpartAccount
from .walletcounterpartwallet import WalletCounterpartWallet
from typing import Union

WalletCounterpart = Union[WalletCounterpartAccount, WalletCounterpartWallet]
