# coding: utf-8

"""
    OpenPay API

    super charge your subscription management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import json
import pprint
import re  # noqa: F401

from aenum import Enum, no_arg


class RoleEnum(str, Enum):
  """
    RoleEnum
    """
  """
    allowed enum values
    """
  ADMIN = 'admin'
  DEVELOPER = 'developer'
  SUPPORT_SPECIALIST = 'support_specialist'
  READ_ONLY = 'read_only'

  @classmethod
  def from_json(cls, json_str: str) -> RoleEnum:
    """Create an instance of RoleEnum from a JSON string"""
    return RoleEnum(json.loads(json_str))
