
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-12T13:41:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc0cd1d77754c629e9a923ec1a04a25f36d76c8c",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
