from .properties_ddf_pb2 import PropertyDeclarationEntry,PropertyDeclarations 
from .lua_ddf_pb2 import LuaModule 
from .gameobject_ddf_pb2 import AcquireInputFocus,CollectionDesc,CollectionInstanceDesc,ComponenTypeDesc,ComponentDesc,ComponentPropertyDesc,Disable,EmbeddedComponentDesc,EmbeddedInstanceDesc,Enable,InstanceDesc,InstancePropertyDesc,PropertyDesc,PrototypeDesc,ReleaseInputFocus,ScriptMessage,ScriptUnrefMessage,SetParent 
