# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sojourner',
                'doc_host': 'https://withmartian.github.io',
                'git_url': 'https://github.com/withmartian/sojourner',
                'lib_path': 'sojourner'},
  'syms': { 'sojourner.core': { 'sojourner.core.Metadata': ('core.html#metadata', 'sojourner/core.py'),
                                'sojourner.core.Metadata.__str__': ('core.html#metadata.__str__', 'sojourner/core.py'),
                                'sojourner.core.Sojourner': ('core.html#sojourner', 'sojourner/core.py'),
                                'sojourner.core.Sojourner.__init__': ('core.html#sojourner.__init__', 'sojourner/core.py'),
                                'sojourner.core.Sojourner.get': ('core.html#sojourner.get', 'sojourner/core.py'),
                                'sojourner.core.Sojourner.list': ('core.html#sojourner.list', 'sojourner/core.py'),
                                'sojourner.core.Sojourner.store': ('core.html#sojourner.store', 'sojourner/core.py'),
                                'sojourner.core.get_storage_client': ('core.html#get_storage_client', 'sojourner/core.py')}}}
