"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import wallet as components_wallet
from dataclasses_json import Undefined, dataclass_json
from formancesdkwallets import utils


@dataclasses.dataclass
class WalletsGetRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class WalletsGetResponseBody:
    r"""The request has succeeded."""
    data: components_wallet.Wallet = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    

