from mqp.client.resource_info import ResourceInfo

# TODO: change this line to the API endpoint you want to test
URL = "https://portal.quantum.lrz.de:4000/"
# TODO: change this to your own token, obviously remove this line in the future
TOKEN = "VMkhNaigWzy1avFEmxcjR25W2Z8fotZfrrEwBkwWBr5f7XB1vxzandtIVGgm5rFB"
# TODO: change this to all the currently available resources
CURRENT_RESOURCES = {
    "Q5": ResourceInfo(
        qubits=5,
        connectivity=[[0, 2], [2, 0], [1, 2], [2, 1], [2, 3], [3, 2], [2, 4], [4, 2]],
        instructions=[
            ("r", {(0,): None, (1,): None, (2,): None, (3,): None, (4,): None}),
            ("id", {(0,): None, (1,): None, (2,): None, (3,): None, (4,): None}),
            (
                "cz",
                {
                    (0, 2): None,
                    (2, 0): None,
                    (1, 2): None,
                    (2, 1): None,
                    (2, 3): None,
                    (3, 2): None,
                    (2, 4): None,
                    (4, 2): None,
                },
            ),
            ("measure", {(0,): None, (1,): None, (2,): None, (3,): None, (4,): None}),
        ],
    ),
    "Q20": ResourceInfo(
        qubits=20,
        connectivity=[
            [0, 1],
            [1, 0],
            [0, 3],
            [3, 0],
            [9, 10],
            [10, 9],
            [9, 14],
            [14, 9],
            [9, 4],
            [4, 9],
            [9, 8],
            [8, 9],
            [10, 11],
            [11, 10],
            [10, 15],
            [15, 10],
            [10, 5],
            [5, 10],
            [11, 16],
            [16, 11],
            [11, 6],
            [6, 11],
            [12, 13],
            [13, 12],
            [12, 7],
            [7, 12],
            [13, 14],
            [14, 13],
            [13, 17],
            [17, 13],
            [13, 8],
            [8, 13],
            [14, 15],
            [15, 14],
            [14, 18],
            [18, 14],
            [15, 16],
            [16, 15],
            [15, 19],
            [19, 15],
            [17, 18],
            [18, 17],
            [18, 19],
            [19, 18],
            [1, 4],
            [4, 1],
            [2, 3],
            [3, 2],
            [2, 7],
            [7, 2],
            [3, 4],
            [4, 3],
            [3, 8],
            [8, 3],
            [4, 5],
            [5, 4],
            [5, 6],
            [6, 5],
            [7, 8],
            [8, 7],
        ],
        instructions=[
            (
                "r",
                {
                    (0,): None,
                    (9,): None,
                    (10,): None,
                    (11,): None,
                    (12,): None,
                    (13,): None,
                    (14,): None,
                    (15,): None,
                    (16,): None,
                    (17,): None,
                    (18,): None,
                    (1,): None,
                    (19,): None,
                    (2,): None,
                    (3,): None,
                    (4,): None,
                    (5,): None,
                    (6,): None,
                    (7,): None,
                    (8,): None,
                },
            ),
            (
                "id",
                {
                    (0,): None,
                    (9,): None,
                    (10,): None,
                    (11,): None,
                    (12,): None,
                    (13,): None,
                    (14,): None,
                    (15,): None,
                    (16,): None,
                    (17,): None,
                    (18,): None,
                    (1,): None,
                    (19,): None,
                    (2,): None,
                    (3,): None,
                    (4,): None,
                    (5,): None,
                    (6,): None,
                    (7,): None,
                    (8,): None,
                },
            ),
            (
                "cz",
                {
                    (0, 1): None,
                    (1, 0): None,
                    (0, 3): None,
                    (3, 0): None,
                    (9, 10): None,
                    (10, 9): None,
                    (9, 14): None,
                    (14, 9): None,
                    (9, 4): None,
                    (4, 9): None,
                    (9, 8): None,
                    (8, 9): None,
                    (10, 11): None,
                    (11, 10): None,
                    (10, 15): None,
                    (15, 10): None,
                    (10, 5): None,
                    (5, 10): None,
                    (11, 16): None,
                    (16, 11): None,
                    (11, 6): None,
                    (6, 11): None,
                    (12, 13): None,
                    (13, 12): None,
                    (12, 7): None,
                    (7, 12): None,
                    (13, 14): None,
                    (14, 13): None,
                    (13, 17): None,
                    (17, 13): None,
                    (13, 8): None,
                    (8, 13): None,
                    (14, 15): None,
                    (15, 14): None,
                    (14, 18): None,
                    (18, 14): None,
                    (15, 16): None,
                    (16, 15): None,
                    (15, 19): None,
                    (19, 15): None,
                    (17, 18): None,
                    (18, 17): None,
                    (18, 19): None,
                    (19, 18): None,
                    (1, 4): None,
                    (4, 1): None,
                    (2, 3): None,
                    (3, 2): None,
                    (2, 7): None,
                    (7, 2): None,
                    (3, 4): None,
                    (4, 3): None,
                    (3, 8): None,
                    (8, 3): None,
                    (4, 5): None,
                    (5, 4): None,
                    (5, 6): None,
                    (6, 5): None,
                    (7, 8): None,
                    (8, 7): None,
                },
            ),
            (
                "measure",
                {
                    (0,): None,
                    (9,): None,
                    (10,): None,
                    (11,): None,
                    (12,): None,
                    (13,): None,
                    (14,): None,
                    (15,): None,
                    (16,): None,
                    (17,): None,
                    (18,): None,
                    (1,): None,
                    (19,): None,
                    (2,): None,
                    (3,): None,
                    (4,): None,
                    (5,): None,
                    (6,): None,
                    (7,): None,
                    (8,): None,
                },
            ),
        ],
    ),
    "QExa20": ResourceInfo(qubits=20, connectivity=None, instructions=None),
    "WMI3": ResourceInfo(qubits=3, connectivity=None, instructions=None),
    "QLM": ResourceInfo(qubits=38, connectivity=None, instructions=None),
}
# TODO: change this to the the qasm you want to test
QASM_FILE = "tests/example.qasm"


def get_qasm() -> str:
    with open(QASM_FILE, "r") as f:
        return f.read()
