# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/edb/v1/hfss_simulation_setup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.edb.v1 import edb_messages_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google.protobuf.empty_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,ansys/api/edb/v1/hfss_simulation_setup.proto\x12\x10\x61nsys.api.edb.v1\x1a#ansys/api/edb/v1/edb_messages.proto\"I\n\x19MeshOpNetLayerInfoMessage\x12\x0b\n\x03net\x18\x01 \x01(\t\x12\r\n\x05layer\x18\x02 \x01(\t\x12\x10\n\x08is_sheet\x18\x03 \x01(\x08\"\x9d\x01\n\x1dSkinDepthMeshOperationMessage\x12\x12\n\nskin_depth\x18\x01 \x01(\t\x12\x1f\n\x17surface_triangle_length\x18\x02 \x01(\t\x12\x12\n\nnum_layers\x18\x03 \x01(\t\x12\x14\n\x0cmax_elements\x18\x04 \x01(\t\x12\x1d\n\x15restrict_max_elements\x18\x05 \x01(\x08\"~\n\x1aLengthMeshOperationMessage\x12\x12\n\nmax_length\x18\x01 \x01(\t\x12\x17\n\x0frestrict_length\x18\x02 \x01(\x08\x12\x14\n\x0cmax_elements\x18\x03 \x01(\t\x12\x1d\n\x15restrict_max_elements\x18\x04 \x01(\x08\"\xee\x02\n\x14MeshOperationMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x12\x15\n\rrefine_inside\x18\x03 \x01(\x08\x12\x13\n\x0bmesh_region\x18\x04 \x01(\t\x12\x43\n\x0enet_layer_info\x18\x05 \x03(\x0b\x32+.ansys.api.edb.v1.MeshOpNetLayerInfoMessage\x12M\n\x12skin_depth_mesh_op\x18\x06 \x01(\x0b\x32/.ansys.api.edb.v1.SkinDepthMeshOperationMessageH\x00\x12\x46\n\x0elength_mesh_op\x18\x07 \x01(\x0b\x32,.ansys.api.edb.v1.LengthMeshOperationMessageH\x00\x12\x14\n\x0csolve_inside\x18\x08 \x01(\x08\x42\x19\n\x17mesh_operation_sub_type\"Q\n\x15MeshOperationsMessage\x12\x38\n\x08mesh_ops\x18\x01 \x03(\x0b\x32&.ansys.api.edb.v1.MeshOperationMessage\"\x8b\x01\n\x1dMeshOperationsPropertyMessage\x12/\n\x06target\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x39\n\x08mesh_ops\x18\x02 \x01(\x0b\x32\'.ansys.api.edb.v1.MeshOperationsMessage2\xdd\x01\n\x1aHfssSimulationSetupService\x12_\n\x11GetMeshOperations\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\'.ansys.api.edb.v1.MeshOperationsMessage\"\x00\x12^\n\x11SetMeshOperations\x12/.ansys.api.edb.v1.MeshOperationsPropertyMessage\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_MESHOPNETLAYERINFOMESSAGE = DESCRIPTOR.message_types_by_name['MeshOpNetLayerInfoMessage']
_SKINDEPTHMESHOPERATIONMESSAGE = DESCRIPTOR.message_types_by_name['SkinDepthMeshOperationMessage']
_LENGTHMESHOPERATIONMESSAGE = DESCRIPTOR.message_types_by_name['LengthMeshOperationMessage']
_MESHOPERATIONMESSAGE = DESCRIPTOR.message_types_by_name['MeshOperationMessage']
_MESHOPERATIONSMESSAGE = DESCRIPTOR.message_types_by_name['MeshOperationsMessage']
_MESHOPERATIONSPROPERTYMESSAGE = DESCRIPTOR.message_types_by_name['MeshOperationsPropertyMessage']
MeshOpNetLayerInfoMessage = _reflection.GeneratedProtocolMessageType('MeshOpNetLayerInfoMessage', (_message.Message,), {
  'DESCRIPTOR' : _MESHOPNETLAYERINFOMESSAGE,
  '__module__' : 'ansys.api.edb.v1.hfss_simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.MeshOpNetLayerInfoMessage)
  })
_sym_db.RegisterMessage(MeshOpNetLayerInfoMessage)

SkinDepthMeshOperationMessage = _reflection.GeneratedProtocolMessageType('SkinDepthMeshOperationMessage', (_message.Message,), {
  'DESCRIPTOR' : _SKINDEPTHMESHOPERATIONMESSAGE,
  '__module__' : 'ansys.api.edb.v1.hfss_simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SkinDepthMeshOperationMessage)
  })
_sym_db.RegisterMessage(SkinDepthMeshOperationMessage)

LengthMeshOperationMessage = _reflection.GeneratedProtocolMessageType('LengthMeshOperationMessage', (_message.Message,), {
  'DESCRIPTOR' : _LENGTHMESHOPERATIONMESSAGE,
  '__module__' : 'ansys.api.edb.v1.hfss_simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.LengthMeshOperationMessage)
  })
_sym_db.RegisterMessage(LengthMeshOperationMessage)

MeshOperationMessage = _reflection.GeneratedProtocolMessageType('MeshOperationMessage', (_message.Message,), {
  'DESCRIPTOR' : _MESHOPERATIONMESSAGE,
  '__module__' : 'ansys.api.edb.v1.hfss_simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.MeshOperationMessage)
  })
_sym_db.RegisterMessage(MeshOperationMessage)

MeshOperationsMessage = _reflection.GeneratedProtocolMessageType('MeshOperationsMessage', (_message.Message,), {
  'DESCRIPTOR' : _MESHOPERATIONSMESSAGE,
  '__module__' : 'ansys.api.edb.v1.hfss_simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.MeshOperationsMessage)
  })
_sym_db.RegisterMessage(MeshOperationsMessage)

MeshOperationsPropertyMessage = _reflection.GeneratedProtocolMessageType('MeshOperationsPropertyMessage', (_message.Message,), {
  'DESCRIPTOR' : _MESHOPERATIONSPROPERTYMESSAGE,
  '__module__' : 'ansys.api.edb.v1.hfss_simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.MeshOperationsPropertyMessage)
  })
_sym_db.RegisterMessage(MeshOperationsPropertyMessage)

_HFSSSIMULATIONSETUPSERVICE = DESCRIPTOR.services_by_name['HfssSimulationSetupService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESHOPNETLAYERINFOMESSAGE._serialized_start=103
  _MESHOPNETLAYERINFOMESSAGE._serialized_end=176
  _SKINDEPTHMESHOPERATIONMESSAGE._serialized_start=179
  _SKINDEPTHMESHOPERATIONMESSAGE._serialized_end=336
  _LENGTHMESHOPERATIONMESSAGE._serialized_start=338
  _LENGTHMESHOPERATIONMESSAGE._serialized_end=464
  _MESHOPERATIONMESSAGE._serialized_start=467
  _MESHOPERATIONMESSAGE._serialized_end=833
  _MESHOPERATIONSMESSAGE._serialized_start=835
  _MESHOPERATIONSMESSAGE._serialized_end=916
  _MESHOPERATIONSPROPERTYMESSAGE._serialized_start=919
  _MESHOPERATIONSPROPERTYMESSAGE._serialized_end=1058
  _HFSSSIMULATIONSETUPSERVICE._serialized_start=1061
  _HFSSSIMULATIONSETUPSERVICE._serialized_end=1282
# @@protoc_insertion_point(module_scope)
