from enum import Enum


class Verwendungszweck(str, Enum):
    """
    Verwendungszweck der Werte Marktlokation
    """

    NETZNUTZUNGSABRECHNUNG = "NETZNUTZUNGSABRECHNUNG"
    BILANZKREISABRECHNUNG = "BILANZKREISABRECHNUNG"
    MEHRMINDERMENGENABRECHNUNG = "MEHRMINDERMENGENABRECHNUNG"
    ENDKUNDENABRECHNUNG = "ENDKUNDENABRECHNUNG"
    UEBERMITTLUNG_AN_DAS_HKNR = "UEBERMITTLUNG_AN_DAS_HKNR"
    ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS = "ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS"
