from .base import BaseModel
from .EEGNet import EEGNet
from .EEGNet_contrastive import EEGNet_contrastive
from .DeepConvNet import DeepConvNet
from .DeepConvNet_contrastive import DeepConvNet_contrastive
from .MIN2Net import MIN2Net
from .MIN2Net_scale import MIN2Net_scale
from .MIN2Net_without_decoder import MIN2Net_without_decoder
from .MIN2Net_without_trp import MIN2Net_without_trp
from .MIN2NetX import MIN2NetX
from .MIN2Net_contrastive import MIN2Net_contrastive
from .MIN2Net_new import MIN2Net_new
from .MIN2Net_SELU import MIN2Net_SELU
from .MIN2Net_contrastive_SELU import MIN2Net_contrastive_SELU
from .MIN2Net_compact import MIN2Net_compact
from .FBMSNet import FBMSNet
from .SpectralSpatialCNN import SpectralSpatialCNN
from .SVM import SVM
from .MIN2Net_original import MIN2Net_original