
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-15T11:34:28-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6141b65cf5ec498d06a27ac666af4a6e6b3317f",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
