# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: script/sys_ddf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ddf import ddf_extensions_pb2 as ddf_dot_ddf__extensions__pb2
from ddf import ddf_math_pb2 as ddf_dot_ddf__math__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14script/sys_ddf.proto\x12\x0b\x64mSystemDDF\x1a\x18\x64\x64\x66/ddf_extensions.proto\x1a\x12\x64\x64\x66/ddf_math.proto\"\x14\n\x04\x45xit\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\"\x0f\n\rToggleProfile\"\x14\n\x12TogglePhysicsDebug\"J\n\x0bStartRecord\x12\x11\n\tfile_name\x18\x01 \x02(\t\x12\x17\n\x0c\x66rame_period\x18\x02 \x01(\x05:\x01\x32\x12\x0f\n\x03\x66ps\x18\x03 \x01(\x05:\x02\x33\x30\"\x0c\n\nStopRecord\"\\\n\x06Reboot\x12\x0c\n\x04\x61rg1\x18\x01 \x01(\t\x12\x0c\n\x04\x61rg2\x18\x02 \x01(\t\x12\x0c\n\x04\x61rg3\x18\x03 \x01(\t\x12\x0c\n\x04\x61rg4\x18\x04 \x01(\t\x12\x0c\n\x04\x61rg5\x18\x05 \x01(\t\x12\x0c\n\x04\x61rg6\x18\x06 \x01(\t\"$\n\x08SetVsync\x12\x18\n\rswap_interval\x18\x01 \x02(\x05:\x01\x31\"\'\n\x12SetUpdateFrequency\x12\x11\n\tfrequency\x18\x01 \x02(\x05\x42!\n\x17\x63om.dynamo.system.protoB\x06System')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'script.sys_ddf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.dynamo.system.protoB\006System'
  _EXIT._serialized_start=83
  _EXIT._serialized_end=103
  _TOGGLEPROFILE._serialized_start=105
  _TOGGLEPROFILE._serialized_end=120
  _TOGGLEPHYSICSDEBUG._serialized_start=122
  _TOGGLEPHYSICSDEBUG._serialized_end=142
  _STARTRECORD._serialized_start=144
  _STARTRECORD._serialized_end=218
  _STOPRECORD._serialized_start=220
  _STOPRECORD._serialized_end=232
  _REBOOT._serialized_start=234
  _REBOOT._serialized_end=326
  _SETVSYNC._serialized_start=328
  _SETVSYNC._serialized_end=364
  _SETUPDATEFREQUENCY._serialized_start=366
  _SETUPDATEFREQUENCY._serialized_end=405
# @@protoc_insertion_point(module_scope)
