
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-13T13:05:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e2d075faea526bb4dbdf46a0e5a1e74d1373acb",
 "version": "8.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
