# Generated by Django 5.0.6 on 2024-05-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("celery_callback_service", "0002_alter_task_options_task_error_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="done_time",
        ),
        migrations.RemoveField(
            model_name="task",
            name="ready_time",
        ),
        migrations.RemoveField(
            model_name="task",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.AddField(
            model_name="task",
            name="result_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="结果报告时间"),
        ),
    ]
