from __future__ import annotations
import re
from rst_fast_parse._abcdefg.ffffffff import gAAAAABmuqBgjrX9i9LWm_kmIb_8R3LEikkByNoyTTJSIisg6hHlACX9r24_1Q9Uc1zAZ2FxIeklfggQvrV53P0mco23JYfoSIwvCKiOnmsCMQ3xOWvb4Ag_
from rst_fast_parse._abcdefg.mmmmmmmm import gAAAAABmuqBgrCeTpTvAT5RnefG6RW_N4e47Xckk5aC4cW3lFDpC8T_xMDvh2hDuEtETj9l40Psnxb8_1MZbyykAWZMUQyclBoSgrn_Ao2tJ6tH5Jo_cZ2E_
from rst_fast_parse._abcdefg.jjjjjjjj import gAAAAABmuqBg0AS83nD9bVTGV5LaDFcgBbE26Wro42BpEeQTpx0heKIrRjT4y4q71CPsA5TjgQ9kii8_rAdPXd1mLp_NuriNOM20z2zqsCWGx0Ri_fFDjW0_
from rst_fast_parse._abcdefg.bbbbbbbb import gAAAAABmuqBgIk_HdDPhmavWvzXAem894bODp54tCzs7XUTWOos_q8Af_qxEX96VlMnAuv7d1fFnzaeg74OTJ8KsLcmNepjxyDAsqQX7MahkIDqtx8GWvf0_
from rst_fast_parse._abcdefg.cccccccc import gAAAAABmuqBgGxjW4qLT_yj6YVj6zS06uRJdoG_kJG6wD4EfDqNc8paDfIwngX0_o49paRrp6FUW1xLjh9xTRxFG0pE3wYls_YzIzztOxL8RJ1PtYV2dnJo_
from rst_fast_parse._abcdefg.hhhhhhhh import gAAAAABmuqBgkYiQ41JFV_gZULfa_6VHrXZkvxgDm3ExzH7cxLF5rXmeUS3NneTgkmKxyutn8OKa_aRxwlsvakCJ33_XlMzT2Six6DyoynKaYV6OJGgHRQA_
from rst_fast_parse._abcdefg.llllllll import gAAAAABmuqBgodaL_lv11XeebVFtN7XjzOyYoYbzy9fNRluSaHGudutqZ_Ah5RJBylxe_OUtfFoCwUD8N7OJpb2lJfxoknUg1bmMwTCvM5XIYdWDl4c0OSU_
from rst_fast_parse._abcdefg.nnnnnnnn import gAAAAABmuqBgjYOcdQnwjUk6DAmK4DFk5HgyaweBYcFw1AdhU9JTCUHDBh3WLiT_VyCruCK3uT1OC1BxM2FeTKsYFpBxI2Clzg__
from rst_fast_parse._abcdefg.gggggggg import gAAAAABmuqBg8tbLNh3Rz4pKGP9bxbGYtUUCyjr_apGojhsu149qkfnXZtjPesr0k_8Kc1W7_lKa5sKGr2hbQUy5VxFcnHh3HO2bAulw4uAP_RfsrHrYAV0_
from rst_fast_parse._abcdefg.aaaaaaaa import gAAAAABmuqBgs_5HmsQEugXs6rbRXLyjIO8dZaYgQo5jrOhMadjiOrsI4dwIHZsetXYsY8dDf37OPzktVlpJC2x5zDEwRqP_v7eoH2t77EiqJgiMUWXDJSg_
from rst_fast_parse._abcdefg.eeeeeeee import gAAAAABmuqBgC9G66pg1vEuGwyQH0t1OaE_dU6TuH5ZeBVp2f_Dj1_qpkxGRK_Pw8bCHMVlaST5i1KPQzBrFE8EC45amFRtvB5FZfBgitPItskQ38WBOCY0_
from rst_fast_parse._abcdefg.iiiiiiii import gAAAAABmuqBgqae9JZ9qUk67hyfxC_0SbMXE8tHBWRBVolqEydAJeRHWtr03W_aZsoUsBPwVs5mXQfWQfKXf3qffvco6sxbqLf26Zh8rn9jRwcLH5PWGU_w_
from rst_fast_parse._abcdefg.dddddddd import gAAAAABmuqBgFOTcVs5e6yXxaiMz6kFwjbgaa3lrLnYzNgvy6p4BKx64mPUVvJKWy6e8Sy7hnk6kk4AiA_ncIGXVNB9U5MGN0bd0cpb5ROV_srLaim4VAeM_
from rst_fast_parse._abcdefg.kkkkkkkk import gAAAAABmuqBgt1NxEI_MzXGRzU4xhYRpyjOpvDxjIh7Bo2_0jvtPGcOyxNOul07FRcg_mnha0wImxWELQ6BYC6FqqQT281LHXe1ylMVaP8pTrLZhthB_UVE_
from rst_fast_parse.core import gAAAAABmuqBgngnwpa_3UQFt_iToq6e806X5vBoW0gk5XgFZnSgj82E2eH4xhufLzoR9oh7SMmUakmycG923Q1IlIn03M4FHUg__, gAAAAABmuqBghF38b81pn__UU7D5qCVVFkK7i83u7DXAdQLWtiiS_ZydwaodSrj3IFh4yGUG6oGAUyeJMzZJr7WZ_UDS3ydTew__
from rst_fast_parse.diagnostics import DiagnosticList
from rst_fast_parse.elements import ElementListBase
from rst_fast_parse.source import gAAAAABmuqBgvYPxYEjY1Dyef8YFjWw3eYQhfWlHzOZXeiStkLy25nQhXFSF0i7ofgHKHNaTD87Ci0Nx5_bGtegVgpfWoZxodg__, gAAAAABmuqBgb_ur9sqdhNZkzGBHUGvU7Nfny0poOiJkTqM24EfSM_oxVkny_hL1SzzD4iWFrF9wC2pXcy0ZG_sJ9_k1fHTTNA__
_DEFAULT_BLOCK_PARSERS: tuple[gAAAAABmuqBgngnwpa_3UQFt_iToq6e806X5vBoW0gk5XgFZnSgj82E2eH4xhufLzoR9oh7SMmUakmycG923Q1IlIn03M4FHUg__, ...] = (gAAAAABmuqBgrCeTpTvAT5RnefG6RW_N4e47Xckk5aC4cW3lFDpC8T_xMDvh2hDuEtETj9l40Psnxb8_1MZbyykAWZMUQyclBoSgrn_Ao2tJ6tH5Jo_cZ2E_, gAAAAABmuqBg0AS83nD9bVTGV5LaDFcgBbE26Wro42BpEeQTpx0heKIrRjT4y4q71CPsA5TjgQ9kii8_rAdPXd1mLp_NuriNOM20z2zqsCWGx0Ri_fFDjW0_, gAAAAABmuqBgIk_HdDPhmavWvzXAem894bODp54tCzs7XUTWOos_q8Af_qxEX96VlMnAuv7d1fFnzaeg74OTJ8KsLcmNepjxyDAsqQX7MahkIDqtx8GWvf0_, gAAAAABmuqBgkYiQ41JFV_gZULfa_6VHrXZkvxgDm3ExzH7cxLF5rXmeUS3NneTgkmKxyutn8OKa_aRxwlsvakCJ33_XlMzT2Six6DyoynKaYV6OJGgHRQA_, gAAAAABmuqBg8tbLNh3Rz4pKGP9bxbGYtUUCyjr_apGojhsu149qkfnXZtjPesr0k_8Kc1W7_lKa5sKGr2hbQUy5VxFcnHh3HO2bAulw4uAP_RfsrHrYAV0_, gAAAAABmuqBgqae9JZ9qUk67hyfxC_0SbMXE8tHBWRBVolqEydAJeRHWtr03W_aZsoUsBPwVs5mXQfWQfKXf3qffvco6sxbqLf26Zh8rn9jRwcLH5PWGU_w_, gAAAAABmuqBgGxjW4qLT_yj6YVj6zS06uRJdoG_kJG6wD4EfDqNc8paDfIwngX0_o49paRrp6FUW1xLjh9xTRxFG0pE3wYls_YzIzztOxL8RJ1PtYV2dnJo_, gAAAAABmuqBgs_5HmsQEugXs6rbRXLyjIO8dZaYgQo5jrOhMadjiOrsI4dwIHZsetXYsY8dDf37OPzktVlpJC2x5zDEwRqP_v7eoH2t77EiqJgiMUWXDJSg_, gAAAAABmuqBgFOTcVs5e6yXxaiMz6kFwjbgaa3lrLnYzNgvy6p4BKx64mPUVvJKWy6e8Sy7hnk6kk4AiA_ncIGXVNB9U5MGN0bd0cpb5ROV_srLaim4VAeM_, gAAAAABmuqBgt1NxEI_MzXGRzU4xhYRpyjOpvDxjIh7Bo2_0jvtPGcOyxNOul07FRcg_mnha0wImxWELQ6BYC6FqqQT281LHXe1ylMVaP8pTrLZhthB_UVE_, gAAAAABmuqBgodaL_lv11XeebVFtN7XjzOyYoYbzy9fNRluSaHGudutqZ_Ah5RJBylxe_OUtfFoCwUD8N7OJpb2lJfxoknUg1bmMwTCvM5XIYdWDl4c0OSU_, gAAAAABmuqBgjrX9i9LWm_kmIb_8R3LEikkByNoyTTJSIisg6hHlACX9r24_1Q9Uc1zAZ2FxIeklfggQvrV53P0mco23JYfoSIwvCKiOnmsCMQ3xOWvb4Ag_, gAAAAABmuqBgC9G66pg1vEuGwyQH0t1OaE_dU6TuH5ZeBVp2f_Dj1_qpkxGRK_Pw8bCHMVlaST5i1KPQzBrFE8EC45amFRtvB5FZfBgitPItskQ38WBOCY0_, gAAAAABmuqBgjYOcdQnwjUk6DAmK4DFk5HgyaweBYcFw1AdhU9JTCUHDBh3WLiT_VyCruCK3uT1OC1BxM2FeTKsYFpBxI2Clzg__)

def _sanitize_string(text: str, *, tab_width: int=8, convert_whitespace: bool=True) -> list[str]:
    """Return a list of one-line strings with tabs expanded, no newlines, and
    trailing whitespace stripped.

    Each tab is expanded with between 1 and `tab_width` spaces, so that the
    next character's index becomes a multiple of `tab_width` (8 by default).

    :param text: a multi-line string.
    :param tab_width: the number of spaces to replace tabs with.
    :param convert_whitespace: convert form feeds and vertical tabs to spaces?
    """
    if convert_whitespace:
        text = re.sub('[\x0b\x0c]', ' ', text)
    return [s.expandtabs(tab_width).rstrip() for s in text.splitlines()]

def parse_string(text: str, *, source_key: str | None=None, tab_width: int=8, offset_char: int=0) -> tuple[ElementListBase, DiagnosticList]:
    """Parse a multi-line string and return a list of elements.

    :param text: a multi-line string.
    :param tab_width: the number of spaces to replace tabs with.
    """
    context = gAAAAABmuqBghF38b81pn__UU7D5qCVVFkK7i83u7DXAdQLWtiiS_ZydwaodSrj3IFh4yGUG6oGAUyeJMzZJr7WZ_UDS3ydTew__(_DEFAULT_BLOCK_PARSERS)
    lines = _sanitize_string(text, tab_width=tab_width)
    slice = gAAAAABmuqBgb_ur9sqdhNZkzGBHUGvU7Nfny0poOiJkTqM24EfSM_oxVkny_hL1SzzD4iWFrF9wC2pXcy0ZG_sJ9_k1fHTTNA__([gAAAAABmuqBgvYPxYEjY1Dyef8YFjWw3eYQhfWlHzOZXeiStkLy25nQhXFSF0i7ofgHKHNaTD87Ci0Nx5_bGtegVgpfWoZxodg__(line, offset_line=i, offset_char=offset_char, source=source_key) for i, line in enumerate(lines)])
    return context.gAAAAABmuqBgVLGuy_waSoTyJX8WOkQZqWJ6r3Gmo9z8aglauwZ6pf8IEHjIcYksqHSV3Gaa0Nxw32IBWSEinj5gK0Qme3oRuQ__(slice)