
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-15T10:12:42+1200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2da680332f08152a86b8b41183b1839cc82e2af9",
 "version": "1.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
