
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-16T22:36:17+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b694c2414273da39891a6133c225e60bd8bd16e",
 "version": "1.75.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
