"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import debitwalletinput as components_debitwalletinput
from ...models.components import hold as components_hold
from dataclasses_json import Undefined, dataclass_json
from formancesdkwallets import utils


@dataclasses.dataclass
class WalletsDebitRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    debit_wallet_input: components_debitwalletinput.DebitWalletInput = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class WalletsDebitResponseBody:
    r"""The request has succeeded and a new resource has been created as a result."""
    data: components_hold.Hold = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    

