# Generated by Django 4.2.15 on 2024-08-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_secure_contact_form", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_subject_prefix",
                    models.CharField(default="Contact Form Submission", max_length=100),
                ),
            ],
        ),
    ]
