
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-06T11:20:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "85b2e62fd91b89c11254075b264fbd2f6931bd03",
 "version": "2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
