"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import trigger as components_trigger
from dataclasses_json import Undefined, dataclass_json
from formancesdkflows import utils
from typing import Callable, List, Optional


@dataclasses.dataclass
class TriggersListRequest:
    name: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'name', 'style': 'form', 'explode': True }})
    cursor: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'cursor', 'style': 'form', 'explode': True }})
    page_size: Optional[int] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'pageSize', 'style': 'form', 'explode': True }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class TriggersListCursor:
    data: List[List[components_trigger.Trigger]] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    next: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('next'), 'exclude': lambda f: f is None }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class TriggersListResponseBody:
    r"""The request has succeeded."""
    cursor: TriggersListCursor = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cursor') }})
    



@dataclasses.dataclass
class TriggersListResponse:
    next: Callable[[], Optional[TriggersListResponse]] = dataclasses.field()
    result: TriggersListResponseBody = dataclasses.field()
    

