from __future__ import annotations
import re
from rst_fast_parse.core import gAAAAABmvnuPNj42qdtIY8ySbUt8SHVpmQrQOLSobwLPYoj3RvNC1jY9pcO0EYhdFzdD_cMsPYESBwfRJcjrzDXWF59zSMUltg2pgUJdIA6tNFRc2rxItPQ_, gAAAAABmvnuPraSvzPr_j2lP7deGTfZusFG7XOVfOBNt_WXSsl_7CxjK1L5ZQh7lRtszllDG4Rb8iUhMCWjDhTgtHlDbOeqrWw__, gAAAAABmvnuPFiNsglZcNLAYt_CC2O1ysbl1SSMD2FRbUir08R6GhJ4_pHfdyZfFLoDODeMiuyT4FlxtDHsHs7Ap_zeSPfIJEoFJExTwUxoIYnI_IhBKuSQ_, gAAAAABmvnuPPyMQkQupnqgLmhaaFYgOZLGB_6PmYhq6Z7EFG7fvQIeBKPWZau_qy3_gK97GQaP9Y21Bt9xfJC2if5OtnVuBGw__
from rst_fast_parse.diagnostics import Diagnostic, DiagnosticCode
from rst_fast_parse.elements import BasicElement
from rst_fast_parse._hijklmn.bbbbbbbb import gAAAAABmvnuPDBw6_4bwPbZim1mxf47_OrSxLwFLzzLDxqoAlTSXH8fAyLwLz36OMf0Bke_8NVrHTJanPdjH0PaYBryfuYVX_w__, gAAAAABmvnuPkSJmEOOQVpk5jXz8JFZU_Ss_ZI3GdmbsTAPA3A43nuI_eQfLMmccm_CLvHOohRoNtCBIbKwud95gmAuxVGpeCHVR2Hr7V6b_21oJKQp4CG8_
from rst_fast_parse._vwxyz import gAAAAABmvnuP_quFKpuYPWz7QdJ1kBaRmIwCQe9rCmHuVZv5Jk1eR82v8o4s8FimCtSYne_H63sWt2aoyl93LrLoAS2foR6HAA__
from rst_fast_parse._opqrstu.ccccffff import gAAAAABmvnuPrsG27_5WLGDs9MOj7eehnuuaCG1u10_HXmxyjCyP2Fq1AGxdyvgksHBIfjAqt8Jp9ic5_m6H_jEOy0xVwD7SEHduR2LtPYqsmPXtv7n1RKE_

def gAAAAABmvnuPFudukSczISc_Ifv8EpfllAyCg9uVD809Ghzx0E0sBeseY60o_BgOvr0CRM4_7UZqaDlF3d6vXzypXoSucrK_2VeHXYnpO3xJ_QUw13_9R18_(gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__: gAAAAABmvnuP_quFKpuYPWz7QdJ1kBaRmIwCQe9rCmHuVZv5Jk1eR82v8o4s8FimCtSYne_H63sWt2aoyl93LrLoAS2foR6HAA__, gAAAAABmvnuPYt9DzGdqMfWNOuwtjka8ZGGeiS1LNy4wgzgDfvlIIqW4pT1dYg5y16iqq00IY__pqD108UHZ2GboK_DTuHleHg__: gAAAAABmvnuPPyMQkQupnqgLmhaaFYgOZLGB_6PmYhq6Z7EFG7fvQIeBKPWZau_qy3_gK97GQaP9Y21Bt9xfJC2if5OtnVuBGw__, diagnostics: gAAAAABmvnuPFiNsglZcNLAYt_CC2O1ysbl1SSMD2FRbUir08R6GhJ4_pHfdyZfFLoDODeMiuyT4FlxtDHsHs7Ap_zeSPfIJEoFJExTwUxoIYnI_IhBKuSQ_, _: gAAAAABmvnuPraSvzPr_j2lP7deGTfZusFG7XOVfOBNt_WXSsl_7CxjK1L5ZQh7lRtszllDG4Rb8iUhMCWjDhTgtHlDbOeqrWw__, /) -> gAAAAABmvnuPNj42qdtIY8ySbUt8SHVpmQrQOLSobwLPYoj3RvNC1jY9pcO0EYhdFzdD_cMsPYESBwfRJcjrzDXWF59zSMUltg2pgUJdIA6tNFRc2rxItPQ_:
    if not (_gAAAAABmvnuPYx_1AJ_ZlGlgvDrehH2B_nIHaCPrE9fnl6NCy1IGzbJUFbt_A6ls0oN30yko4kcNJOnUTmBis7jsENh0h5ePEw__ := gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__.gAAAAABmvnuPYx_1AJ_ZlGlgvDrehH2B_nIHaCPrE9fnl6NCy1IGzbJUFbt_A6ls0oN30yko4kcNJOnUTmBis7jsENh0h5ePEw__):
        return gAAAAABmvnuPNj42qdtIY8ySbUt8SHVpmQrQOLSobwLPYoj3RvNC1jY9pcO0EYhdFzdD_cMsPYESBwfRJcjrzDXWF59zSMUltg2pgUJdIA6tNFRc2rxItPQ_.gAAAAABmvnuPRbdlsfvazMgv6xfcLvNC0QmLZyLevZAFSsO0gN3crEdWh85I5fK4AkyiRNRbEPJDXyQKddWPenhSD_uYCxVoJg__
    if not re.match(gAAAAABmvnuPDBw6_4bwPbZim1mxf47_OrSxLwFLzzLDxqoAlTSXH8fAyLwLz36OMf0Bke_8NVrHTJanPdjH0PaYBryfuYVX_w__, _gAAAAABmvnuPYx_1AJ_ZlGlgvDrehH2B_nIHaCPrE9fnl6NCy1IGzbJUFbt_A6ls0oN30yko4kcNJOnUTmBis7jsENh0h5ePEw__.content):
        return gAAAAABmvnuPNj42qdtIY8ySbUt8SHVpmQrQOLSobwLPYoj3RvNC1jY9pcO0EYhdFzdD_cMsPYESBwfRJcjrzDXWF59zSMUltg2pgUJdIA6tNFRc2rxItPQ_.gAAAAABmvnuPMhZZtYqBwgmlntAnk2pNEzm4IuBVbAOgcNUNPk5cwtS0ORGVXbj_bY3x708WqH8FacqCobgWvhXy_PI3HCP44A__
    if not (table_slice := gAAAAABmvnuPG0CRq5__dYml_W6_TT7g_UQGcp4Tx6JzGaLrTQTTkTYexkryvXOwYfXQmz4UrYfYwc_IZw82HWnHdHGVt_CYEXVNxR9lfj3ww_I8IeX0fkw_(gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__, diagnostics)):
        return gAAAAABmvnuPNj42qdtIY8ySbUt8SHVpmQrQOLSobwLPYoj3RvNC1jY9pcO0EYhdFzdD_cMsPYESBwfRJcjrzDXWF59zSMUltg2pgUJdIA6tNFRc2rxItPQ_.gAAAAABmvnuP_ClUFKNcZK3izoScss_N4ceBj9LXWkx42Msjc8XGvV8pQ0jcSFPd7BXVi3Qh2svvdS7_7MW5pdxsyUOXMvFZBw__
    if (first := table_slice.gAAAAABmvnuPYx_1AJ_ZlGlgvDrehH2B_nIHaCPrE9fnl6NCy1IGzbJUFbt_A6ls0oN30yko4kcNJOnUTmBis7jsENh0h5ePEw__) and (last := table_slice.gAAAAABmvnuPtSk5A9h7uoFTW9kQc_J179me2SXQYV0xfUAjl9qCaFt0mzEf2Um6Ld_aFscHpO2rxlifxEZAlIVBvvMQKO5aMg__):
        gAAAAABmvnuPYt9DzGdqMfWNOuwtjka8ZGGeiS1LNy4wgzgDfvlIIqW4pT1dYg5y16iqq00IY__pqD108UHZ2GboK_DTuHleHg__.append(BasicElement('table_simple', (first.line, last.line)))
        gAAAAABmvnuPrsG27_5WLGDs9MOj7eehnuuaCG1u10_HXmxyjCyP2Fq1AGxdyvgksHBIfjAqt8Jp9ic5_m6H_jEOy0xVwD7SEHduR2LtPYqsmPXtv7n1RKE_(diagnostics, gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__, 'Simple table')
    return gAAAAABmvnuPNj42qdtIY8ySbUt8SHVpmQrQOLSobwLPYoj3RvNC1jY9pcO0EYhdFzdD_cMsPYESBwfRJcjrzDXWF59zSMUltg2pgUJdIA6tNFRc2rxItPQ_.gAAAAABmvnuP_ClUFKNcZK3izoScss_N4ceBj9LXWkx42Msjc8XGvV8pQ0jcSFPd7BXVi3Qh2svvdS7_7MW5pdxsyUOXMvFZBw__

def gAAAAABmvnuPG0CRq5__dYml_W6_TT7g_UQGcp4Tx6JzGaLrTQTTkTYexkryvXOwYfXQmz4UrYfYwc_IZw82HWnHdHGVt_CYEXVNxR9lfj3ww_I8IeX0fkw_(gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__: gAAAAABmvnuP_quFKpuYPWz7QdJ1kBaRmIwCQe9rCmHuVZv5Jk1eR82v8o4s8FimCtSYne_H63sWt2aoyl93LrLoAS2foR6HAA__, diagnostics: gAAAAABmvnuPFiNsglZcNLAYt_CC2O1ysbl1SSMD2FRbUir08R6GhJ4_pHfdyZfFLoDODeMiuyT4FlxtDHsHs7Ap_zeSPfIJEoFJExTwUxoIYnI_IhBKuSQ_) -> None | gAAAAABmvnuP_quFKpuYPWz7QdJ1kBaRmIwCQe9rCmHuVZv5Jk1eR82v8o4s8FimCtSYne_H63sWt2aoyl93LrLoAS2foR6HAA__:
    if not (first_line := gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__.gAAAAABmvnuPYx_1AJ_ZlGlgvDrehH2B_nIHaCPrE9fnl6NCy1IGzbJUFbt_A6ls0oN30yko4kcNJOnUTmBis7jsENh0h5ePEw__):
        return None
    toplen = len(first_line.content.strip())
    borders_found: int = 0
    peek_offset = 1
    last_border_offset: None | int = None
    while (line := gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__.gAAAAABmvnuPuZXbXRIn_Z6uW7rl1b6tjkrw7FbiBfqZUZMylVWsCG9X6PO5txqGZgMgnn879eyop15Pa9oKq7BJnPqu2HDIpA__(peek_offset)):
        if re.match(gAAAAABmvnuPkSJmEOOQVpk5jXz8JFZU_Ss_ZI3GdmbsTAPA3A43nuI_eQfLMmccm_CLvHOohRoNtCBIbKwud95gmAuxVGpeCHVR2Hr7V6b_21oJKQp4CG8_, line.content):
            if len(line.content.strip()) != toplen:
                diagnostics.append(Diagnostic(DiagnosticCode.table_malformed, 'Bottom/header table border does not match top border.', line.line))
                gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__.gAAAAABmvnuPp_QE9_WnXWVDZg5oKVJ6LQ5CVrdrh1cxtPKUkZZB8K9_AZTE7wd9z5Ah21eEusDJcgxVmRcYg1wa0BtlMgWtfg__(peek_offset)
                return None
            borders_found += 1
            last_border_offset = peek_offset
            if borders_found == 2 or not (next_line := gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__.gAAAAABmvnuPuZXbXRIn_Z6uW7rl1b6tjkrw7FbiBfqZUZMylVWsCG9X6PO5txqGZgMgnn879eyop15Pa9oKq7BJnPqu2HDIpA__(peek_offset + 1)) or next_line.gAAAAABmvnuPPkZGuVG7rySsIzxg5qGN25cViT_kH2yqB1Jh4YgWuHYFeCggnKOC9aN7z3D2A8_1OQHaFV7ltGyYeMGtrldIWg__:
                break
        peek_offset += 1
    else:
        if last_border_offset is not None:
            message = 'No bottom table border found or no blank line after table bottom.'
            gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__.gAAAAABmvnuPp_QE9_WnXWVDZg5oKVJ6LQ5CVrdrh1cxtPKUkZZB8K9_AZTE7wd9z5Ah21eEusDJcgxVmRcYg1wa0BtlMgWtfg__(last_border_offset)
        else:
            message = 'No bottom table border found.'
            gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__.gAAAAABmvnuPp_QE9_WnXWVDZg5oKVJ6LQ5CVrdrh1cxtPKUkZZB8K9_AZTE7wd9z5Ah21eEusDJcgxVmRcYg1wa0BtlMgWtfg__(peek_offset)
        diagnostics.append(Diagnostic(DiagnosticCode.table_malformed, message, first_line.line))
        return None
    table_slice = gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__.gAAAAABmvnuPuitFRunLAjfPGmxTYo7EoUVGkMDC8TEnYWWRJf5fCxlbqrS1OkLkbJ8rYzBGr8RfF_uDqtF7LQ7KJLw4meIjNQ__(0, peek_offset + 1)
    gAAAAABmvnuPgOUfWLYnhgj_rZE4eyrpzmgA4RGoTLKXgRLXDrHsLiZCW02GShxQcPj1_ZEQnz4C9__S7bV35h8f_PETntG5SQ__.gAAAAABmvnuPp_QE9_WnXWVDZg5oKVJ6LQ5CVrdrh1cxtPKUkZZB8K9_AZTE7wd9z5Ah21eEusDJcgxVmRcYg1wa0BtlMgWtfg__(peek_offset)
    return table_slice