
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-13T20:53:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7562fcb754fcf4aee9243f2c268c519cba8c2f78",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
