# coding: utf-8

"""
    Platform API

    _OpenAPI specification for the **Platform API** of **Empire**, the allocation and nomination platform of BritNed_  ---  Additional documentation available in the API's [GitHub repository](https://github.com/britned/empire-platform-api) 

    The version of the OpenAPI document: 4.0.0
    Contact: britned.info@britned.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from empire_platform_api_public_client.models.participant_overview_data_finance_overview import ParticipantOverviewDataFinanceOverview  # noqa: E501

class TestParticipantOverviewDataFinanceOverview(unittest.TestCase):
    """ParticipantOverviewDataFinanceOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ParticipantOverviewDataFinanceOverview:
        """Test ParticipantOverviewDataFinanceOverview
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ParticipantOverviewDataFinanceOverview`
        """
        model = ParticipantOverviewDataFinanceOverview()  # noqa: E501
        if include_optional:
            return ParticipantOverviewDataFinanceOverview(
                credit_cover = 1.337,
                credit_utilization = 1.337,
                credit_limit = 1.337
            )
        else:
            return ParticipantOverviewDataFinanceOverview(
                credit_cover = 1.337,
                credit_utilization = 1.337,
                credit_limit = 1.337,
        )
        """

    def testParticipantOverviewDataFinanceOverview(self):
        """Test ParticipantOverviewDataFinanceOverview"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
