
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-12T15:36:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6eed2e27675ba1e8f50986e52d7ba5c25d95dc49",
 "version": "1.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
