# Generated by Django 4.2.1 on 2023-05-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_discount_invoice_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='draft',
        ),
        migrations.AddField(
            model_name='company',
            name='annual_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('N', 'New'), ('V', 'Validated'), ('C', 'Repaid'), ('X', 'Closed'), ('F', 'Funded'), ('R', 'Rejected'), ('W', 'Withdrawn'), ('A', 'For Amendment'), ('AP', 'Awaiting Payment')], default='N', max_length=30),
        ),
    ]
