# Generated by Django 4.2.5 on 2023-11-10 08:01

import core_models.app.models.invoice
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_invoice_bill_of_lading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='corporate'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='third_party_id',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bill_of_lading',
            field=models.FileField(blank=True, null=True, upload_to=core_models.app.models.invoice.doc_upload_to),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('N', 'New'), ('BV', 'Validated by Buyer'), ('V', 'Validated'), ('C', 'Repaid'), ('X', 'Closed'), ('F', 'Funded'), ('R', 'Rejected'), ('W', 'Withdrawn'), ('A', 'For Amendment'), ('AP', 'Awaiting Payment'), ('O', 'Overdue')], default='N', max_length=30),
        ),
        migrations.CreateModel(
            name='VertoConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('api_key', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verto_config', to='app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
