# Generated by Django 4.2.5 on 2023-11-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_bankaccount_account_type_bankaccount_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
