# Generated by Django 4.2.5 on 2023-11-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_bankaccount_company_bankaccount_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractinformation',
            name='past_invoices',
        ),
        migrations.AddField(
            model_name='contractinformation',
            name='credit_notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='app.contractdocument'),
        ),
        migrations.AlterField(
            model_name='contractinformation',
            name='length_of_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contractinformation',
            name='type_of_product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
