# Generated by Django 4.2.5 on 2023-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_contractinformation_past_invoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinformation',
            name='completed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
