# Generated by Django 4.2.5 on 2024-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_bankaccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='require_buyer_invoice_approval',
            field=models.BooleanField(default=True),
        ),
    ]
