# Generated by Django 4.2.5 on 2024-05-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_contract_require_buyer_invoice_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='company', max_length=30),
        ),
    ]
