# Generated by Django 4.2.5 on 2024-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_notificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='status',
            field=models.CharField(default='Uploaded', max_length=30),
        ),
    ]
