# Generated by Django 4.2.5 on 2024-07-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_company_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='automation_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
