# Generated by Django 4.2.14 on 2024-08-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_contract_automation_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfiguration',
            name='buyer_countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='buyer_config_countries', to='app.country'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='seller_config_countries', to='app.country'),
        ),
    ]
