from typing import Optional
import numpy

class Image:
    name: str
    data: Optional[numpy.ndarray]
    def width(self) -> int:
        ...
    def height(self) -> int:
        ...
    def is_external(self) -> bool:
        ...
    def is_embedded(self) -> bool:
        ...
    def save(self, path: str):
        ...
    def embed(self, path: str):
        ...
