from typing import Iterator
from .layer import Layer

class Layers:
    def new_quads(self) -> Layer:
        ...
    def new_sounds(self) -> Layer:
        ...
    def new_tiles(self, width: int, height: int) -> Layer:
        ...
    def new_game(self, width: int, height: int) -> Layer:
        ...
    def new_physics(self, kind: str) -> Layer:
        ...
    def __iter__(self) -> Iterator[Layer]:
        ...
    def __next__(self) -> Layer:
        ...
    def __getitem__(self, index: int) -> Layer:
        ...
