from typing import Iterator
from .quad import Quad

class Quads:
    def new(self, pos_x: float, pos_y: float, width: float, height: float) -> Quad:
        ...
    def __iter__(self) -> Iterator[Quad]:
        ...
    def __next__(self) -> Quad:
        ...
    def __getitem__(self, index: int) -> Quad:
        ...
