# Generated by Django 4.0.10 on 2024-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='添加时间')),
                ('mod_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('uid', models.CharField(blank=True, max_length=64, null=True, verbose_name='唯一码')),
                ('status', models.IntegerField(blank=True, choices=[(0, '新建'), (10, '就绪'), (20, '执行中'), (30, '完成')], null=True, verbose_name='状态')),
                ('ready_time', models.DateTimeField(blank=True, null=True, verbose_name='就绪时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('done_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('args_raw', models.TextField(blank=True, null=True, verbose_name='args')),
                ('kwargs_raw', models.TextField(blank=True, null=True, verbose_name='kwargs')),
                ('service', models.CharField(max_length=512, verbose_name='服务函数')),
                ('celery_task_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Celery任务ID')),
                ('celery_task_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Celery任务创建时间')),
            ],
            options={
                'verbose_name': '异步任务',
                'verbose_name_plural': '异步任务',
            },
        ),
    ]
