# Generated by Django 4.0.10 on 2024-05-22 22:39

from django.db import migrations, models
import django_safe_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('celery_callback_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '回调任务', 'verbose_name_plural': '回调任务'},
        ),
        migrations.AddField(
            model_name='task',
            name='error_data',
            field=django_safe_fields.fields.SafeTextField(blank=True, null=True, verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='task',
            name='execution_lock_timeout',
            field=models.IntegerField(default=60, verbose_name='任务执行锁定时长'),
        ),
        migrations.AddField(
            model_name='task',
            name='result_data',
            field=django_safe_fields.fields.SafeTextField(blank=True, null=True, verbose_name='结果信息'),
        ),
        migrations.AddField(
            model_name='task',
            name='success',
            field=models.BooleanField(blank=True, null=True, verbose_name='成功'),
        ),
    ]
