
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-17T00:50:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "106190191e261730d1993539e20c851185870199",
 "version": "3.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
