
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-16T17:10:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7d9bf49f682de8d2ef51f4617e3da782400c290",
 "version": "2024.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
