# Generated by Django 3.2.12 on 2022-07-24 18:36

from django.db import migrations


def populate_kioblog_settings(apps, schema_editor):
    setting_model = apps.get_model('kioblog', 'Meta')
    setting_model.objects.get_or_create(key='blog_title', value='Blog Title')
    setting_model.objects.get_or_create(key='meta_description', value='Meta Description')
    setting_model.objects.get_or_create(key='meta_title', value='Meta Title')


class Migration(migrations.Migration):

    dependencies = [
        ('kioblog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_kioblog_settings),
    ]
