"""
    EMIL InsuranceService

    The EMIL InsuranceService API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.insurance
from eis.insurance.model.policy_partner_role_class import PolicyPartnerRoleClass
globals()['PolicyPartnerRoleClass'] = PolicyPartnerRoleClass
from eis.insurance.model.update_policy_partner_role_response_class import UpdatePolicyPartnerRoleResponseClass


class TestUpdatePolicyPartnerRoleResponseClass(unittest.TestCase):
    """UpdatePolicyPartnerRoleResponseClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdatePolicyPartnerRoleResponseClass(self):
        """Test UpdatePolicyPartnerRoleResponseClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdatePolicyPartnerRoleResponseClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
