
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-14T08:55:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b08a7976f8ef700de3c8f757ad62e03c62505d0",
 "version": "8.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
