# Generated by Django 4.2 on 2023-04-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_name_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='onboarding_stage',
            field=models.IntegerField(default=1),
        ),
    ]
