# Generated by Django 4.2.2 on 2023-06-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_country_region_subregion_city_alter_company_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
    ]
