# Generated by Django 4.2.1 on 2023-07-04 22:55

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_sector_remove_company_industry_configuration_rpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='rpa',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Use {seller_first_name}, {seller_last_name}, {seller_company_name}, {seller_address}, {buyer_first_name}, {buyer_last_name}, {buyer_company_name}, {buyer_address}, {financier_first_name}, {financier_last_name}, {financier_company_name}, {financier_address}, {current_day}, {current_month}, {current_year}, {discount_percent}, {discount_amount}, {invoice_amount}, ', null=True),
        ),
    ]
