# Generated by Django 4.2.1 on 2023-07-05 15:16

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_configuration_rpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rpa',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, editable=False, null=True),
        ),
    ]
