# Generated by Django 4.2.4 on 2023-08-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_otp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='country',
            name='oecd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileapplication',
            name='status',
            field=models.CharField(choices=[('R', 'Rejected'), ('A', 'Approved'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
