# Generated by Django 4.2.5 on 2023-10-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_commercialinformation_credit_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_of_lading',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profileapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
