# Generated by Django 4.2.5 on 2023-12-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_contractinformation_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
