# Generated by Django 4.2.5 on 2023-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_bankaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='percent_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(choices=[('R', 'Rejected'), ('A', 'Approved'), ('P', 'Processing')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated: This is the amount that will be paid back by the Buyer', max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='financier_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated: This is the amount paid by Financier', max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated: This is the amount that goes to the Financier as interest/profit', max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='seller_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated: This is the amount that is sent to SME', max_digits=30),
        ),
    ]
