# Generated by Django 4.2.5 on 2023-12-11 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_baserate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='percent_discount',
        ),
        migrations.AddField(
            model_name='baserate',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='buyer_risk_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='facility_discount',
            field=models.FloatField(default=0, help_text='Auto-picked from Base Rate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='seller_risk_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baserate',
            name='duration',
            field=models.IntegerField(help_text='Maturity in months'),
        ),
        migrations.AlterField(
            model_name='baserate',
            name='rate',
            field=models.FloatField(help_text='Rate in percentage'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='base_rate',
            field=models.FloatField(default=0, help_text='Auto-picked from Base Rate'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer_risk_percentage',
            field=models.FloatField(default=0, help_text='Auto-picked from Contract'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='seller_risk_percentage',
            field=models.FloatField(default=0, help_text='Auto-picked from Contract'),
        ),
    ]
