# Generated by Django 4.2.5 on 2024-01-25 15:36

import cities_light.abstract_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_companyconfiguration_company_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='corporate'),
        ),
        migrations.AlterField(
            model_name='city',
            name='search_names',
            field=cities_light.abstract_models.ToSearchTextField(blank=True, default='', max_length=4000),
        ),
    ]
