# Generated by Django 4.2.5 on 2024-01-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_user_company_admin_alter_bankaccount_account_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='companyy',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='financier',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='seller',
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('seller_company', 'buyer_company')},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='seller',
        ),
    ]
