# Generated by Django 4.2.5 on 2024-03-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_user_address_remove_user_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='corporate', max_length=30),
        ),
    ]
