# Generated by Django 4.2.5 on 2024-07-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_companydocument_rejection_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractinformation',
            name='credit_notes',
        ),
        migrations.AddField(
            model_name='contractinformation',
            name='sales_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_ledgers', to='app.contractdocument'),
        ),
    ]
