# Generated by Django 4.2.5 on 2024-07-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_contractinformation_automation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='kyc_status_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
