
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-16T19:19:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a13d6578e242737f326564ce6a8d2397262144b4",
 "version": "1.75.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
