"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import workflowinstance as components_workflowinstance
from dataclasses_json import Undefined, dataclass_json
from formancesdkflows import utils
from typing import Callable, List, Optional


@dataclasses.dataclass
class InstancesListRequest:
    workflow_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'workflowId', 'style': 'form', 'explode': True }})
    running: bool = dataclasses.field(metadata={'query_param': { 'field_name': 'running', 'style': 'form', 'explode': True }})
    cursor: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'cursor', 'style': 'form', 'explode': True }})
    page_size: Optional[int] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'pageSize', 'style': 'form', 'explode': True }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Cursor:
    data: List[components_workflowinstance.WorkflowInstance] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    next: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('next'), 'exclude': lambda f: f is None }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class InstancesListResponseBody:
    r"""The request has succeeded."""
    cursor: Cursor = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cursor') }})
    



@dataclasses.dataclass
class InstancesListResponse:
    next: Callable[[], Optional[InstancesListResponse]] = dataclasses.field()
    result: InstancesListResponseBody = dataclasses.field()
    

