"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import workflow as components_workflow
from dataclasses_json import Undefined, dataclass_json
from formancesdkflows import utils
from typing import Callable, List, Optional


@dataclasses.dataclass
class WorkflowsListRequest:
    cursor: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'cursor', 'style': 'form', 'explode': True }})
    page_size: Optional[int] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'pageSize', 'style': 'form', 'explode': True }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class WorkflowsListCursor:
    data: List[components_workflow.Workflow] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    next: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('next'), 'exclude': lambda f: f is None }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class WorkflowsListResponseBody:
    r"""The request has succeeded."""
    cursor: WorkflowsListCursor = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cursor') }})
    



@dataclasses.dataclass
class WorkflowsListResponse:
    next: Callable[[], Optional[WorkflowsListResponse]] = dataclasses.field()
    result: WorkflowsListResponseBody = dataclasses.field()
    

