
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-17T00:39:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9d4c17af4e4dc140c16b7e7230505fbc4a61850",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
