# Generated by Django 2.2.8 on 2022-01-03 10:23

import django.core.validators
from django.db import migrations, models

import ip_whitelist.validators


class Migration(migrations.Migration):
    dependencies = [
        ("ip_whitelist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allowedip",
            name="address",
            field=models.CharField(
                max_length=45,
                unique=True,
                validators=[django.core.validators.validate_ipv46_address],
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="allowediprange",
            name="range",
            field=models.CharField(
                max_length=49,
                unique=True,
                validators=[ip_whitelist.validators.validate_allowed_range_field],
                verbose_name="Range",
            ),
        ),
    ]
