# Generated by Django 3.2 on 2024-02-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_whitelist', '0002_auto_20220103_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='allowediprange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
