
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-14T11:24:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2572677a1b06a53a72c1fbfa593b616b3134914",
 "version": "3.0.0rc17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
