
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-13T21:19:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ff8a621b2acd43c3657b56e2ceb2dc924dbc8416",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
