from typing import Iterator
import numpy

from .image import Image

class Images:
    def new_from_file(self, path: str) -> Image:
        ...
    def new_external(self, name: str) -> Image:
        ...
    def new_from_data(self, name: str, py_array3: numpy.ndarray) -> Image:
        ...
    def __iter__(self) -> Iterator[Image]:
        ...
    def __next__(self) -> Image:
        ...
    def __getitem__(self, index: int) -> Image:
        ...
