# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DataDetailingCheckTypeCIBasicTypes(str, Enum):
    """
    DataDetailingCheckTypeCIBasicTypes
    """

    """
    allowed enum values
    """
    NONE = 'none'
    BOLT2BOLTTOOSMALL = 'bolt2BoltTooSmall'
    BOLT2EGDETOOSMALL = 'bolt2EgdeTooSmall'
    MINIMUMPLATETHICKNESSFORBOLTS = 'minimumPlateThicknessForBolts'
    MAXIMUMPLATETHICKNESSFORBOLTSCONSIDERINGDUCTILITY = 'maximumPlateThicknessForBoltsConsideringDuctility'
    PRELOADEDBOLTSANDBEARINGBOLTSUSEDTOGETHER = 'preloadedBoltsAndBearingBoltsUsedTogether'
    BEARINGBOLTSANDWELDSUSEDTOGETHER = 'bearingBoltsAndWeldsUsedTogether'
    BOLTGRIPLENGTHTOOBIG = 'boltGripLengthTooBig'
    SINGLEBOLTEDGEDISTANCESPACINGRATIOTOOSMALL = 'singleBoltEdgeDistanceSpacingRatioTooSmall'
    MULTIPLEBOLTSEDGEDISTANCESPACINGRATIOTOOSMALL = 'multipleBoltsEdgeDistanceSpacingRatioTooSmall'
    MULTIPLEBOLTSSPACINGDISTANCESPACINGRATIOTOOSMALL = 'multipleBoltsSpacingDistanceSpacingRatioTooSmall'
    WELDTOOSMALL = 'weldTooSmall'
    WELDTOOSMALLRECOMMENDED = 'weldTooSmallRecommended'
    WELDTOOSMALLCONSIDERINGDUCTILITY = 'weldTooSmallConsideringDuctility'
    WELDTOOBIG = 'weldTooBig'
    WELDTOOSHORT = 'weldTooShort'
    MINIMUMPLATETHICKNESSFORWELDS = 'minimumPlateThicknessForWelds'
    WELDMAXIMUMULTIMATESTRENGTH = 'weldMaximumUltimateStrength'
    CHECKNOTEXECUTED = 'checkNotExecuted'
    PINMINIMUMCLEAREDGEDISTANCE = 'pinMinimumClearEdgeDistance'
    PINMINIMUMCLEARENDDISTANCE = 'pinMinimumClearEndDistance'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DataDetailingCheckTypeCIBasicTypes from a JSON string"""
        return cls(json.loads(json_str))


