from __future__ import annotations
import re
from rst_fast_parse._abcdefg.ffffffff import gAAAAABmuydMUoO_qums8W3_TsZRXrWBPWyEwvX_We2FRc9ZzKiWqLi5mko2cFVypj0YSILZ6XtVj_gy_s9rHdanzI6xkWz4D32U6U3eybXDwHE8_XNUsa4_
from rst_fast_parse._abcdefg.mmmmmmmm import gAAAAABmuydMhDRx3eESVWiuy_vJiHP6MEfSs__OkpnHRAUuqYCiu75Wc6p8hMfh4ztanIxU9ZybivdzR4S_srUyOlTWUaCqTqfA33_psWyPk6EgCib0MVI_
from rst_fast_parse._abcdefg.jjjjjjjj import gAAAAABmuydMuRBu8Ayz1O7LY1Fr3lG8_ytvH6zE7LbU_h9_uFdy8azoyNZqR0HTJftY6PLLqQyLq2t56FvU21cviK9bvxcjDYYgeXvReWffrkAEOAHVG2E_
from rst_fast_parse._abcdefg.bbbbbbbb import gAAAAABmuydMp42X7dE3UQc4_VIpE4YxW1_UYPRG7Rjr7VpRl8pulVhBiV5GxrkGHQUyz4FBEK_2AC4g4OPECBklHPtO9AyGHR68ljtYcjYSv41p8Te_21Q_
from rst_fast_parse._abcdefg.cccccccc import gAAAAABmuydMnBU1cRJgTjts2RPUo2vEiWzueUm974ovJjsohokVcjiu0GHxoCtZ34vEgHPc2jr5MAqX6lE7FVldb1O_tP2LOyXAa0lA9kOZIlCT1h2q4xU_
from rst_fast_parse._abcdefg.hhhhhhhh import gAAAAABmuydMsjihxBLjS0g_mxLtLpHidYZWF5WqcVNd58NgcaDMutXOl1D6xBg8w_XBnMdDszy8ygYDx6x_48ZUelZ9Neb3fpYnCLxhoa__CpjYrOsqI_o_
from rst_fast_parse._abcdefg.llllllll import gAAAAABmuydM1W2PvsmnRNPl1zjCEgcPPJs84W2e_nYj2Sz9QMghfkDV4BCmsD_aggt3lctorJhZFuIxurp1jjoZS0x_bFqeGc1Q0JD3C8aT8eQkrH9ekL0_
from rst_fast_parse._abcdefg.nnnnnnnn import gAAAAABmuydMS1adGH_315P3lgIZ_HOj8if5yfV3gRIo5AkPKLOLGJRJD5vRAS_qWnrwRRlPcssqDnYQK9bH7BRg83I7REbQVQ__
from rst_fast_parse._abcdefg.gggggggg import gAAAAABmuydMJBZD5qqbUqTa_VBIp955qlRD_DUI0Qm5CkSV9EJq5riQJlpFUlzYhoRD6a5X5ra7TmlANn66741oSRIAOjawuqVi35p1ip3RKL_wxfbVNT8_
from rst_fast_parse._abcdefg.aaaaaaaa import gAAAAABmuydMFQoYVRroxTsd4sVFHsrrXdUo_JXWopQ_6KCA4zA5qrpxJZPse4vpEpP2QFbB6E2BzquGOylsNxepWgQcx8pU3LGQ_uTsCR2EUZ3rfzXf3Vw_
from rst_fast_parse._abcdefg.eeeeeeee import gAAAAABmuydMvLkYFnb1V3CxYXdtK7WQi5ftOJqmjSn9Bvfuu8oP1tmYXRkwktHEwt_PCl9Gld50MGEifGBvzePgaEX7uCQttwLDNdj5aIQqItLPQYdPEbk_
from rst_fast_parse._abcdefg.iiiiiiii import gAAAAABmuydMXW9yvxUimpZitcC_HKoe4TQ8Ex9qDB33DNhFUcL4qYAH7s6cr6soGK6Vjs5yZp_wXtbfBP2YLHtDO_9kDRJE1jjjyTcUaaRdS_p330vRvAw_
from rst_fast_parse._abcdefg.dddddddd import gAAAAABmuydMe6h6lB_70_njJyhMZpAC_YSTu_jZyjugDl7WDByucqQ_RK5a9RBN7E9jNxBDfrzDlAJpxncYV1NtOx7Jou0WL5hLoOTw0Bk4PaFWu9NZO3k_
from rst_fast_parse._abcdefg.kkkkkkkk import gAAAAABmuydM0lDusGnBilTXsDAA0Yr_lZFkrbOkJ5F3NKh7lfbBLZtZToIM9qdRyaTdzjPUQJ84Ttzl2BAUxr3zFiAGV9tQx2aIDyI_fzcxtyPT6WX3bNI_
from rst_fast_parse.core import gAAAAABmuydMtmqQaUlCZC3V5hjKqkxx9csQRUj_mgRSUSqp9ECcAOmQtULRKUHk4iaztn7LuBruXi7Du_NqkYrCqLfoQgo23g__, gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__
from rst_fast_parse.diagnostics import DiagnosticList
from rst_fast_parse.elements import ElementListBase
from rst_fast_parse.source import gAAAAABmuydMXewr3wJ9aJ_2oIUAd34ETU2PfImZCzr9dibAm1dDUhVjXqrLNQa6EyIEe9o4Jt2ZoVKep67m4IX1R_dzZ0qHTA__, gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__
_DEFAULT_BLOCK_PARSERS: tuple[gAAAAABmuydMtmqQaUlCZC3V5hjKqkxx9csQRUj_mgRSUSqp9ECcAOmQtULRKUHk4iaztn7LuBruXi7Du_NqkYrCqLfoQgo23g__, ...] = (gAAAAABmuydMhDRx3eESVWiuy_vJiHP6MEfSs__OkpnHRAUuqYCiu75Wc6p8hMfh4ztanIxU9ZybivdzR4S_srUyOlTWUaCqTqfA33_psWyPk6EgCib0MVI_, gAAAAABmuydMuRBu8Ayz1O7LY1Fr3lG8_ytvH6zE7LbU_h9_uFdy8azoyNZqR0HTJftY6PLLqQyLq2t56FvU21cviK9bvxcjDYYgeXvReWffrkAEOAHVG2E_, gAAAAABmuydMp42X7dE3UQc4_VIpE4YxW1_UYPRG7Rjr7VpRl8pulVhBiV5GxrkGHQUyz4FBEK_2AC4g4OPECBklHPtO9AyGHR68ljtYcjYSv41p8Te_21Q_, gAAAAABmuydMsjihxBLjS0g_mxLtLpHidYZWF5WqcVNd58NgcaDMutXOl1D6xBg8w_XBnMdDszy8ygYDx6x_48ZUelZ9Neb3fpYnCLxhoa__CpjYrOsqI_o_, gAAAAABmuydMJBZD5qqbUqTa_VBIp955qlRD_DUI0Qm5CkSV9EJq5riQJlpFUlzYhoRD6a5X5ra7TmlANn66741oSRIAOjawuqVi35p1ip3RKL_wxfbVNT8_, gAAAAABmuydMXW9yvxUimpZitcC_HKoe4TQ8Ex9qDB33DNhFUcL4qYAH7s6cr6soGK6Vjs5yZp_wXtbfBP2YLHtDO_9kDRJE1jjjyTcUaaRdS_p330vRvAw_, gAAAAABmuydMnBU1cRJgTjts2RPUo2vEiWzueUm974ovJjsohokVcjiu0GHxoCtZ34vEgHPc2jr5MAqX6lE7FVldb1O_tP2LOyXAa0lA9kOZIlCT1h2q4xU_, gAAAAABmuydMFQoYVRroxTsd4sVFHsrrXdUo_JXWopQ_6KCA4zA5qrpxJZPse4vpEpP2QFbB6E2BzquGOylsNxepWgQcx8pU3LGQ_uTsCR2EUZ3rfzXf3Vw_, gAAAAABmuydMe6h6lB_70_njJyhMZpAC_YSTu_jZyjugDl7WDByucqQ_RK5a9RBN7E9jNxBDfrzDlAJpxncYV1NtOx7Jou0WL5hLoOTw0Bk4PaFWu9NZO3k_, gAAAAABmuydM0lDusGnBilTXsDAA0Yr_lZFkrbOkJ5F3NKh7lfbBLZtZToIM9qdRyaTdzjPUQJ84Ttzl2BAUxr3zFiAGV9tQx2aIDyI_fzcxtyPT6WX3bNI_, gAAAAABmuydM1W2PvsmnRNPl1zjCEgcPPJs84W2e_nYj2Sz9QMghfkDV4BCmsD_aggt3lctorJhZFuIxurp1jjoZS0x_bFqeGc1Q0JD3C8aT8eQkrH9ekL0_, gAAAAABmuydMUoO_qums8W3_TsZRXrWBPWyEwvX_We2FRc9ZzKiWqLi5mko2cFVypj0YSILZ6XtVj_gy_s9rHdanzI6xkWz4D32U6U3eybXDwHE8_XNUsa4_, gAAAAABmuydMvLkYFnb1V3CxYXdtK7WQi5ftOJqmjSn9Bvfuu8oP1tmYXRkwktHEwt_PCl9Gld50MGEifGBvzePgaEX7uCQttwLDNdj5aIQqItLPQYdPEbk_, gAAAAABmuydMS1adGH_315P3lgIZ_HOj8if5yfV3gRIo5AkPKLOLGJRJD5vRAS_qWnrwRRlPcssqDnYQK9bH7BRg83I7REbQVQ__)

def _sanitize_string(text: str, *, tab_width: int=8, convert_whitespace: bool=True) -> list[str]:
    """Return a list of one-line strings with tabs expanded, no newlines, and
    trailing whitespace stripped.

    Each tab is expanded with between 1 and `tab_width` spaces, so that the
    next character's index becomes a multiple of `tab_width` (8 by default).

    :param text: a multi-line string.
    :param tab_width: the number of spaces to replace tabs with.
    :param convert_whitespace: convert form feeds and vertical tabs to spaces?
    """
    if convert_whitespace:
        text = re.sub('[\x0b\x0c]', ' ', text)
    return [s.expandtabs(tab_width).rstrip() for s in text.splitlines()]

def parse_string(text: str, *, source_key: str | None=None, tab_width: int=8, offset_char: int=0) -> tuple[ElementListBase, DiagnosticList]:
    """Parse a multi-line string and return a list of elements.

    :param text: a multi-line string.
    :param tab_width: the number of spaces to replace tabs with.
    """
    context = gAAAAABmuydMiLdU_dp59oVEPGBNv68vj5wG7_22Bvg5bZ03OT2G_QCzmRWERmHgVHtQYXo1mUcSENx4LswwbgB9jit4vTIw9A__(_DEFAULT_BLOCK_PARSERS)
    lines = _sanitize_string(text, tab_width=tab_width)
    slice = gAAAAABmuydMVJgMnmSTyLrkYdxKPQdHOKbYiMjkRU_PfqS4fOZ24_zmOB0oCtkvC_ztGe1VFoNh5MyXYh8V_BBPR27wINYhDg__([gAAAAABmuydMXewr3wJ9aJ_2oIUAd34ETU2PfImZCzr9dibAm1dDUhVjXqrLNQa6EyIEe9o4Jt2ZoVKep67m4IX1R_dzZ0qHTA__(line, offset_line=i, offset_char=offset_char, source=source_key) for i, line in enumerate(lines)])
    return context.gAAAAABmuydMviZRBCvAA_Ra_womfSOKe6Sqk35acZmbv8ogNp_JDzdOtpgoiqExwDrer3ykWn3XWJiLVPyYHHA3_PAuIITpeQ__(slice)