"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import hold as components_hold
from dataclasses_json import Undefined, dataclass_json
from formancesdkwallets import utils


@dataclasses.dataclass
class HoldsGetRequest:
    hold_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'holdId', 'style': 'simple', 'explode': False }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class HoldsGetResponseBody:
    r"""The request has succeeded."""
    data: components_hold.Hold = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    

