"""etiket_v_0.1.1

Revision ID: 37e90d5a09bb
Revises: 71e0bcc916d6
Create Date: 2023-12-09 10:44:25.615174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e90d5a09bb'
down_revision: Union[str, None] = '71e0bcc916d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'notes')
    # ### end Alembic commands ###
